import type { RoiIndicador } from './roteiro-roi-radiologia';

/**
 * ROI — Roteiro Objetivo de Inspeção da ANVISA: SERVIÇO EAC TIPO III
 * (LABORATÓRIO CLÍNICO) (documento 13.1, versão 1.2, de 02/08/2023),
 * baseado na RDC nº 786/2023.
 *
 * Mesma estrutura dos demais ROI (roteiro-roi-radiologia.ts,
 * roteiro-roi-odontologia.ts): 56 indicadores avaliados numa escala de 0 a 5
 * (NOTA_CONFORME = 3). Diferente do roteiro de dedetizadoras/Roteiro Único de
 * Radiologia, esta fonte já trazia a coluna de criticidade (C/NC) —
 * transcrita diretamente, sem julgamento próprio. Conteúdo extraído do PDF
 * oficial anexado (roi laboratorio.pdf) — não editar à mão sem conferir com
 * o PDF: os textos são a redação legal usada como fundamentação no
 * relatório.
 */
export const ROI_LABORATORIO: RoiIndicador[] = [
  {
    numero: 1,
    indicador: 'Alvará de Licenciamento',
    criticidade: 'C',
    baseLegal: 'Artigos 28, 36 e 37 da RDC 786/2023',
    alternativas: [
      'Sem alvará de licenciamento ou equivalente.',
      'Alvará de licenciamento vencido, sem pedido de renovação ou em processo inicial de licenciamento.',
      'Alvará de licenciamento vencido, com pedido de renovação.',
      'Dispõe de alvará de licenciamento ou equivalente, expedido pelo órgão sanitário competente, indicando as atividades relacionadas ao EAC.',
      'Alvará de licenciamento atualizado, com pedido de renovação.',
      'Solicitou a renovação do alvará de licenciamento antes do vencimento nos últimos dois anos.',
    ],
  },
  {
    numero: 2,
    indicador: 'Projeto Básico de Arquitetura (PBA) e memorial descritivo',
    criticidade: 'NC',
    baseLegal: 'Art. 34 da RDC 63/2011 e Inciso I do Art. 83 da RDC 786/2023',
    alternativas: [
      'Não possui PBA e/ou memorial descritivo.',
      'O serviço realizou modificações, sem solicitar a VISA e/ou sem atualizar o PBA ou memorial descritivo.',
      'O serviço possui PBA e memorial descritivo atualizados e protocolado na VISA para avaliação.',
      'O serviço possui Projeto Básico de Arquitetura (PBA) e memorial descritivo atualizados e aprovado pela Vigilância Sanitária.',
      'PBA e memorial descritivo revisados anualmente para verificação de possíveis adequações.',
      'Existe procedimento interno estabelecendo a necessidade de atualização e aprovação do PBA e do memorial descritivo na VISA antes de qualquer intervenção no serviço.',
    ],
  },
  {
    numero: 3,
    indicador: 'Responsável Técnico',
    criticidade: 'C',
    baseLegal: 'Artigos 30, 38 e 39 da RDC 786/2023',
    alternativas: [
      'Não possui Responsável Técnico, nem substituto formalmente designados.',
      'Possui Responsável Técnico, porém não dispõe de substituto ou o Responsável Técnico não desempenha a função.',
      'O Responsável Técnico ou substituto, designado formalmente, difere daquele que desempenha na prática a função.',
      'Possui Responsável Técnico legalmente habilitado e, em caso de impedimento deste, dispõe de profissional legalmente habilitado para substituí-lo.',
      'RT é exclusivo do serviço.',
      'RT e substituto são exclusivos do serviço e presentes no estabelecimento em seu funcionamento.',
    ],
  },
  {
    numero: 4,
    indicador: 'Serviço de EAC Itinerante Tipo III',
    criticidade: 'C',
    baseLegal: 'Artigos 40 e 41 da RDC 786/2023',
    alternativas: [
      'Presta assistência com sua estrutura física em movimento ou não realiza as medidas e verificações após montagem do instrumento no local de parada.',
      'As medidas e verificações após a montagem do instrumento são realizadas apenas em algumas paradas.',
      'Não apresenta registros de todas as medidas e verificações após a montagem do instrumento no local de parada para atendimento.',
      'Presta assistência com sua estrutura física apenas quando não está em movimento. Realiza medidas e verificações após a montagem do instrumento no local de parada para atendimento, mantendo os registros.',
      'Possui protocolo para início das atividades após a parada, indicando que todas as medidas e verificações foram realizadas.',
      'Possui sistema informatizado, com supervisão, autorizando o início das atividades.',
    ],
  },
  {
    numero: 5,
    indicador: 'Contratualização das Atividades',
    criticidade: 'C',
    baseLegal: 'Artigos 43, 47 e 48 da RDC 786/2023',
    alternativas: [
      'Não há contratualização ou as partes não comprovam a regularidade sanitária.',
      'Há contratualização, mas não constam as obrigações, responsabilidades ou funções das partes.',
      'Há contratualização, porém não estabelece os critérios de controle de qualidade e/ou de qualificação das etapas da cadeia do EAC.',
      'As contratualizações das atividades relacionadas aos EAC estabelecem as responsabilidades das Partes envolvidas e os critérios de controle e de qualificação das etapas da cadeia do EAC. As partes requisitam documento que comprova a regularidade sanitária da outra parte. Há contrato escrito onde constam as obrigações, responsabilidades e funções das partes.',
      'O contrato possui período de validade e está vigente.',
      'Existe protocolo para revisão e atualização periódica dos contratos.',
    ],
  },
  {
    numero: 6,
    indicador: 'Conteúdo do Contrato',
    criticidade: 'NC',
    baseLegal: 'Incisos I, II, III, IV, V, VI, VII e VIII do Art. 48 da RDC 786/2023',
    alternativas: [
      'Contrato não possui nenhum dos 8 requisitos estabelecidos no artigo 48 da RDC 786/2023.',
      'Contrato prevê até 4 dos 8 requisitos estabelecidos.',
      'Contrato prevê de 5 a 7 dos 8 requisitos estabelecidos.',
      'Está previsto no contrato: I- autorização expressa para que as Partes promovam auditorias para fins de verificação do cumprimento da RDC 786/2023; II- o fluxo de registros para controle de rastreabilidade; III- o cumprimento de todos os requisitos das fases analíticas, pré-analíticas e pós-analítica da RDC 786/2023; IV- que as Partes comuniquem entre si desvios de qualidade e riscos identificados em tempo hábil para implementação de medidas corretivas; V- que as Partes forneçam todas as informações necessárias à outra Parte para garantia de uma operação segura e com redução de riscos; VI- a Parte responsável pela notificação das Doenças de Notificação Compulsórias; VII- que as Partes monitorem e revisem o desempenho, requerendo à outra Parte a implementação de melhorias necessárias; VIII- que as Partes cumpram os requisitos dispostos na RDC 786/2023.',
      'Possui profissional designado para a gestão do contrato.',
      'Existe previsão de auditorias periódicas para verificar o cumprimento contratual.',
    ],
  },
  {
    numero: 7,
    indicador: 'Contrato de Supervisão',
    criticidade: 'C',
    baseLegal: 'Art. 10 (§ 1º), 15 (§ 1º) e 49 da RDC 786/2023',
    alternativas: [
      'Não existe contrato de Supervisão.',
      'Contrato de supervisão em elaboração.',
      'Contrato de supervisão com período de vigência expirado.',
      'Caso o EAC possua serviços Tipo I ou II vinculado, existe contrato de supervisão.',
      'O contrato possui período de validade e está vigente.',
      'Existe protocolo para revisão e atualização periódica dos contratos.',
    ],
  },
  {
    numero: 8,
    indicador: 'Conteúdo do Contrato de Supervisão',
    criticidade: 'NC',
    baseLegal: 'Incisos I, II, III, IV e V do Art. 49 da RDC 786/2023',
    alternativas: [
      'Contrato de supervisão não possui nenhum dos 5 requisitos estabelecidos no artigo 49 da RDC 786/2023.',
      'Contrato de supervisão prevê até 3 dos 5 requisitos estabelecidos.',
      'Contrato de supervisão prevê 4 dos 5 requisitos estabelecidos.',
      'O contrato de supervisão contém, minimamente: I - a obrigação das Partes de definirem as responsabilidades de modo a garantir a gestão da qualidade, o gerenciamento dos processos operacionais e a gestão do controle da qualidade nos termos desta Resolução; II - a obrigação das Partes de fornecerem todas as informações necessárias à outra Parte para garantir uma operação segura e com redução de riscos; III - a obrigação das Partes de monitorarem e revisarem o desempenho, requerendo à outra Parte medidas para implementação de qualquer melhoria necessária; IV - a competência do Serviço Tipo III em promover os controles de desempenho para a outra Parte; e V - a obrigação de cada Parte para assegurar o cumprimento dos requisitos de controle interno e externo de qualidade.',
      'Possui profissional designado para a gestão do contrato.',
      'Existe previsão de auditorias periódicas para verificar o cumprimento contratual.',
    ],
  },
  {
    numero: 9,
    indicador: 'Gerenciamento de Tecnologias',
    criticidade: 'NC',
    baseLegal: 'Art. 54 da RDC 63/2011 e Artigos 55, 56 e 59 (§ 2°) da RDC 786/2023',
    alternativas: [
      'Não possui PGT ou utiliza produtos sujeitos à vigilância sanitária que não estão regularizados junto à Anvisa ou não realiza o gerenciamento de suas tecnologias.',
      'PGT em elaboração.',
      'PGT não está atualizado.',
      'Possui Plano de Gerenciamento de Tecnologias, contemplando inclusive os instrumentos dos serviços tipo I e tipo II com o qual mantém contrato de supervisão (quando aplicável). Todos os produtos sujeitos à vigilância sanitária, utilizados pelo Serviço que executa EAC, estão regularizados junto à Anvisa e são utilizados exclusivamente para os fins a que se destinam. Realiza o gerenciamento de suas tecnologias, no que diz respeito às condições de seleção, aquisição, transporte, recebimento, armazenamento, distribuição, instalação, calibração, funcionamento ou uso, descarte e rastreabilidade.',
      'O Plano é avaliado sistematicamente quando da introdução de novas tecnologias no setor e ações de conformidade e prevenção de recorrência são registradas.',
      'O plano e sua implementação recebem auditoria externa anualmente.',
    ],
  },
  {
    numero: 10,
    indicador: 'Notificações (Incidentes, eventos adversos e queixas técnicas)',
    criticidade: 'NC',
    baseLegal: 'Art. 57 da RDC 786/2023',
    alternativas: [
      'Não notificam incidentes, eventos adversos e queixas técnicas ocorridos.',
      'Não realiza as notificações sistematicamente, tendo sido verificada ocorrência não notificada.',
      'Monitora o desempenho e segurança dos produtos sob vigilância sanitária e oferta de serviços, bem como adota estratégias para identificar e notificar, através do Notivisa, incidentes, eventos adversos e queixas técnicas ocorridos. Porém, não investiga as ocorrências e/ou não adota medidas para prevenir a recorrência.',
      'Monitora o desempenho e segurança dos produtos sob vigilância sanitária e oferta de serviços, bem como adota estratégias para identificar e notificar, através do Notivisa, incidentes, eventos adversos e queixas técnicas ocorridos. Investiga as ocorrências e adota medidas para prevenir a recorrência.',
      'Possui procedimento operacional padrão ou instrução técnica para notificações (incidentes, eventos adversos e queixas técnicas).',
      'Realiza avaliação da efetividade das medidas implantadas para prevenir repetição de recorrência.',
    ],
  },
  {
    numero: 11,
    indicador: 'Manutenções dos Instrumentos',
    criticidade: 'C',
    baseLegal: 'Art. 59 da RDC 786/2023',
    alternativas: [
      'Não são realizadas manutenções preventivas nem corretivas.',
      'As manutenções não são realizadas em alguns dos instrumentos, ou realiza apenas manutenções corretivas e não há calendário para manutenções preventivas.',
      'Há registro da manutenção corretiva e preventiva, porém em periodicidade diferente do indicado pelo fabricante ou superior a um ano (instrumentos cujo fabricante não delimita a periodicidade).',
      'Mantém registro da manutenção preventiva e corretiva dos instrumentos de acordo com as instruções de uso. Na ausência de definição do fabricante do instrumento quanto à periodicidade de manutenção preventiva e corretiva, o Serviço estabelece a periodicidade, devendo ser executada com frequência, no mínimo, anual.',
      'Planejamento com calendário de manutenção e registros informatizados.',
      'Existe um sistema de gerenciamento das manutenções dos instrumentos com profissional designado para coordenação. Participam de Comissão de Tecnovigilância.',
    ],
  },
  {
    numero: 12,
    indicador: 'Verificação de Conformidade dos Instrumentos (aceitação e desempenho)',
    criticidade: 'C',
    baseLegal: 'Art. 60 da RDC 786/2023',
    alternativas: [
      'Não realiza medidas e verificações dos instrumentos ou realizou apenas as medidas de aceitação.',
      'Realiza medidas de aceitação e desempenho apenas de alguns instrumentos.',
      'Realiza as medidas e verificações conforme periodicidade definida, porém não realizou as medidas iniciais após a montagem.',
      'Realiza medidas e verificações após a montagem do instrumento no ambiente para atestar a conformidade com as características de projeto e de desempenho declaradas pelo fabricante (aceitação), bem como determina sua periodicidade de execução (desempenho), mantendo os registros.',
      'Monitora a evolução temporal de todas as avaliações, com alerta para valores fora das tolerâncias.',
      'Possui sistema informatizado de gerenciamento das medidas e verificações.',
    ],
  },
  {
    numero: 13,
    indicador: 'Calibração dos Instrumentos',
    criticidade: 'C',
    baseLegal: 'Art. 61 da RDC 786/2023',
    alternativas: [
      'Instrumentos não são calibrados.',
      'Os instrumentos são calibrados conforme a periodicidade recomendada pelo fabricante, porém em laboratórios que não são acreditados por organismos de acreditação signatários de acordos de reconhecimento mútuo.',
      'Os instrumentos são calibrados em laboratórios acreditados por organismos de acreditação signatários de acordos de reconhecimento mútuo, porém em desacordo com a periodicidade recomendada pelo fabricante.',
      'Os instrumentos são calibrados em laboratórios acreditados por organismos de acreditação signatários de acordos de reconhecimento mútuo, conforme a periodicidade recomendada pelo fabricante. Na ausência da indicação de periodicidade por parte do fabricante, esta é estabelecida pelo serviço que executa EAC, sendo executada com frequência, no mínimo, anual.',
      'Realiza análise crítica dos certificados de calibração, estabelecendo os parâmetros de aceitação.',
      'Possui sistema informatizado de gerenciamento das calibrações.',
    ],
  },
  {
    numero: 14,
    indicador: 'Gerenciamento de Risco',
    criticidade: 'NC',
    baseLegal: 'Art. 75 da RDC 786/2023',
    alternativas: [
      'Não realiza gerenciamento de risco.',
      'Gerenciamento de risco não contempla pelo menos dois dos quatro tópicos descritos.',
      'Gerenciamento de risco não contempla pelo menos um dos quatro tópicos descritos.',
      'O gerenciamento de riscos contempla, no mínimo: I- identificação, análise, avaliação, tratamento, monitoramento e comunicação dos riscos; II- identificação de possíveis falhas de instrumentos e erros humanos que possam resultar em incidentes relacionados à assistência à saúde e promoção das medidas preventivas necessárias; III- investigação documentada que determine as causas das possíveis falhas de instrumento, erros humanos ou descumprimento das normativas em vigor, suas consequências e as ações preventivas e corretivas necessárias; e IV- execução das ações preventivas e corretivas identificadas durante as investigações.',
      'Registros das ações de Gerenciamento de Riscos em meio digital, com cópia de segurança (backup).',
      'Registros das ações de Gerenciamento de Riscos em meio digital, com cópia de segurança (backup) e monitora o gerenciamento de risco através de indicadores estabelecidos na instituição.',
    ],
  },
  {
    numero: 15,
    indicador: 'Gestão de Documentos',
    criticidade: 'NC',
    baseLegal: 'Artigos 81, 82 e 83 da RDC 786/2023',
    alternativas: [
      'Não dispõe dos documentos atualizados e disponíveis.',
      'Dispõe de parte dos documentos atualizados e disponíveis.',
      'Mantém atualizados e disponíveis em meio físico ou eletrônico todos os documentos, porém não há controle das alterações nos registros contendo data, nome ou assinatura legalmente válida do responsável pela alteração, preservando o dado original.',
      'Mantém atualizados e disponíveis em meio físico ou eletrônico: I- PBA e memorial descritivo aprovados pela autoridade sanitária competente; II- relação e registros de todos os procedimentos realizados; III- inventário dos produtos sujeitos à vigilância sanitária; IV- relação nominal de toda a equipe, suas atribuições, qualificação e cargas horárias; V- registros que evidenciam a execução dos Programas de Educação Permanente e Garantia de Qualidade; e VI- registros de resultados dos programas de Ensaios de Proficiência e Controle Interno da Qualidade. Toda a documentação e registros de que trata a RDC 786/2023 são mantidos e arquivados pelo prazo mínimo de cinco anos. As alterações nos registros contêm data, nome ou assinatura legalmente válida do responsável pela alteração, preservando o dado original.',
      'Possui protocolo para revisão anual dos documentos.',
      'Documentos disponíveis em meio digital, com cópia de segurança (backup).',
    ],
  },
  {
    numero: 16,
    indicador: 'Gestão de Pessoal',
    criticidade: 'C',
    baseLegal: 'Artigos 86, 88 e 89 da RDC 786/2023',
    alternativas: [
      'Equipe subdimensionada para o perfil de demanda e/ou não possui profissional legalmente habilitado como supervisor do pessoal.',
      'Possui equipe dimensionada de acordo com seu perfil de demanda e em conformidade com o estabelecido nas demais normativas aplicáveis. Dispõe de profissional legalmente habilitado como supervisor do pessoal técnico, porém somente durante parte do período de funcionamento e/ou não dispõe de substituto.',
      'Equipe dimensionada de acordo com seu perfil de demanda. Dispõe de profissional legalmente habilitado como supervisor do pessoal técnico durante todo seu período de funcionamento, em caso de impedimento possui profissional legalmente habilitado para substituí-lo. Porém, não mantém registro da formação e qualificação de seus profissionais compatíveis com as funções desempenhadas.',
      'Possui equipe dimensionada de acordo com seu perfil de demanda e em conformidade com o estabelecido nas demais normativas aplicáveis. Dispõe de profissional legalmente habilitado como supervisor do pessoal técnico durante todo seu período de funcionamento; em caso de impedimento, possui profissional legalmente habilitado para substituí-lo. Mantém registro da formação e qualificação de seus profissionais compatíveis com as funções desempenhadas.',
      'Possui cadastro de reserva de profissionais, para atendimento de possíveis aumentos de demanda ou ausências não previstas.',
      'Possui cadastro de reserva de profissionais com capacitação atualizada, para atendimento de possíveis aumentos de demanda ou ausências não previstas.',
    ],
  },
  {
    numero: 17,
    indicador: 'Programa de Educação Permanente',
    criticidade: 'NC',
    baseLegal: 'Artigos 90 e 91 da RDC 786/2023',
    alternativas: [
      'Não implementa Programa de Educação Permanente.',
      'Implementa o Programa de Educação Permanente apenas para parte da equipe ou não realiza anualmente.',
      'Realiza as capacitações com frequência mínima de um ano, porém não realiza avaliações para demonstrar a eficácia das ações de capacitação e treinamento.',
      'Implementa Programa de Educação Permanente para toda a equipe, contemplando: I- capacitações e treinamentos inicial e periódicos, com frequência mínima anual; II- capacitações e treinamentos teóricos e práticos baseados em abordagens de riscos, sempre que novos processos, técnicas ou tecnologias forem implementados, ou antes de novas pessoas integrarem o processo; e III- metodologia de avaliação de forma a demonstrar eficácia das ações de capacitação e treinamento.',
      'O Programa de Educação Permanente é valorizado na instituição, sendo item determinante na avaliação de desempenho dos profissionais.',
      'O serviço promove a participação dos profissionais em cursos e eventos externos na área de atuação e disponibiliza materiais didáticos para estudos complementares.',
    ],
  },
  {
    numero: 18,
    indicador: 'Conteúdo das Capacitações e Treinamentos',
    criticidade: 'NC',
    baseLegal: 'Artigos 92 e 93 da RDC 786/2023',
    alternativas: [
      'Não há registros.',
      'Há registros das capacitações e treinamentos, porém com informações incompletas.',
      'Há registros contendo data, horário, carga horária, conteúdo ministrado, nome e a formação ou capacitação profissional do instrutor e dos trabalhadores envolvidos, porém as capacitações e treinamentos não contemplam todos os tópicos exigidos.',
      'As capacitações e treinamentos periódicos contemplam, no mínimo, os seguintes tópicos: I- instruções escritas; II- segurança do paciente; III- gerenciamento dos riscos inerentes às tecnologias utilizadas; e IV- Programa de Garantia de Qualidade. Há registros contendo data, horário, carga horária, conteúdo ministrado, nome e a formação ou capacitação profissional do instrutor e dos trabalhadores envolvidos.',
      'Revisa o Plano de Capacitação anualmente, atualizando o conteúdo.',
      'Realiza as capacitações com periodicidade inferior a um ano.',
    ],
  },
  {
    numero: 19,
    indicador: 'Infraestrutura, Climatização e PMOC',
    criticidade: 'NC',
    baseLegal: 'Artigos 18, 26 e 27 da RDC 786/2023; Art. 35 da RDC 63/2011; Itens 7.5 e 7.5.1 da Parte III da RDC 50/2002; Artigos 5º, 6º e anexo da Portaria 3523/1998; Art. 1º da Lei 13.589/2018',
    alternativas: [
      'A infraestrutura do serviço de EAC não está de acordo com a RDC 50 ou a sala de execução de EAC não dispõe de climatização ou a iluminação prejudica a avaliação da coloração da pele do paciente.',
      'A infraestrutura do serviço de EAC está de acordo com a RDC 50 e existe sistema de climatização, porém visivelmente em más condições de limpeza, manutenção, operação e controle.',
      'A infraestrutura do serviço de EAC está de acordo com a RDC 50 e o sistema de climatização em condições adequadas de limpeza, manutenção, operação e controle, porém sem os devidos registros e/ou não existe controle da qualidade do ar conforme normas regulamentadoras.',
      'A infraestrutura está de acordo com a RDC 50. A sala de execução de EAC dispõe de sistema de climatização em condições adequadas de limpeza, manutenção, operação e controle com registro. Existe controle da qualidade do ar interno seguindo normas regulamentadoras e Plano de Manutenção, Operação e Controle (PMOC).',
      'Mantém PMOC atualizado e cumpre as atividades estipuladas dentro da periodicidade estabelecida, bem como as recomendações a serem adotadas em situações de falha do equipamento e de emergência com os devidos registros.',
      'Existe um programa de gerenciamento das condições de climatização do serviço de saúde, com relatórios de análise técnica e registro de análise de problemas e ações de melhorias adotadas.',
    ],
  },
  {
    numero: 20,
    indicador: 'Plano de Gerenciamento de Resíduos - PGRSS',
    criticidade: 'NC',
    baseLegal: 'Art. 23, Inciso X, da RDC 63/2011; Art. 2º, Art. 5º e inciso XI do Art. 6º da RDC 222/2018; Art. 77 da RDC 786/2023',
    alternativas: [
      'Não possui Plano de Gerenciamento de Resíduos de Serviços de Saúde.',
      'O PGRSS está em elaboração.',
      'O PGRSS está incompleto ou desatualizado e/ou não possui cópia do contrato e licença ambiental vigentes da empresa terceirizada responsável pela destinação final dos RSS.',
      'Possui Plano de Gerenciamento de Resíduos, implementado efetivamente, e dispõe de cópia do contrato e licença ambiental vigentes da empresa terceirizada responsável pela destinação final dos RSS.',
      'O PGRSS está disponível em formato físico e eletrônico para consulta no serviço. É sistematicamente avaliado e ações de conformidades são registradas.',
      'O laboratório clínico dispõe de Licença Ambiental.',
    ],
  },
  {
    numero: 21,
    indicador: 'Controle de Pragas',
    criticidade: 'NC',
    baseLegal: 'Inciso VIII do Art. 23, Art. 63 da RDC 63/2011 e Art. 4º da RDC 622/2022',
    alternativas: [
      'Não há registro do controle, sendo verificada a presença significativa de pragas/vetores no serviço.',
      'Realiza terceirização do serviço, com empresa sem licença sanitária.',
      'Realiza ações de controle, mas foi verificada a presença eventual de pragas/vetores.',
      'Garante ações eficazes e contínuas de controle de vetores e pragas. Quando necessário, o controle químico é realizado por empresa habilitada, possuidora de licença sanitária e ambiental, com produtos desinfestantes regularizados pela Anvisa. Mantém disponível documentação e registro referente ao controle de vetores e pragas urbanas.',
      'Realiza em periodicidade definida as ações de controle.',
      'Possui rotina de verificação da efetividade do controle, implementando possíveis ações corretivas.',
    ],
  },
  {
    numero: 22,
    indicador: 'Controle da Qualidade da Água e Limpeza do Reservatório',
    criticidade: 'NC',
    baseLegal: 'Inciso VI do Art. 23, Art. 39 (§1º e §2º) da RDC 63/2011',
    alternativas: [
      'Não há controle de qualidade da água ou registro de limpeza dos reservatórios de água.',
      'Existem alguns registros de limpeza dos reservatórios e controle de qualidade, mas sem periodicidade.',
      'Existem os registros de controle de qualidade da água, mas a limpeza dos reservatórios não foi realizada nos últimos seis meses.',
      'Realiza a limpeza dos reservatórios de água a cada seis meses, mantendo o registro da capacidade e da limpeza periódica. Existe documentação e registro referente ao controle da qualidade da água (laudo de análise).',
      'Possui sistema de monitoramento da qualidade da água e limpeza dos reservatórios.',
      'Possui sistema informatizado de monitoramento da qualidade da água e limpeza dos reservatórios, com indicação de alertas.',
    ],
  },
  {
    numero: 23,
    indicador: 'Manutenção da Estrutura Física',
    criticidade: 'NC',
    baseLegal: 'Artigos 23 Inciso VII, 36 e 42 da RDC 63/2011',
    alternativas: [
      'Estrutura física apresenta-se degradada com presença de mofo, infiltrações ou desgastes que comprometem a segurança dos processos, e não há registro de manutenção.',
      'Estrutura física apresenta-se degradada em algumas áreas. Apresentaram registro de manutenções corretivas.',
      'Estrutura física conservada, mas não há registro de manutenções preventivas, apenas das manutenções corretivas.',
      'Serviço de saúde mantém as instalações físicas em boas condições de conservação e realiza ações de manutenção preventiva e corretiva das instalações prediais, de forma própria ou terceirizada, e existem registros.',
      'Existe plano de manutenção predial.',
      'Possui sistema informatizado de manutenção predial preventiva e corretiva.',
    ],
  },
  {
    numero: 24,
    indicador: 'Armazenamento dos produtos de diagnóstico in vitro e material biológico',
    criticidade: 'C',
    baseLegal: 'Art. 62 da RDC 786/2023',
    alternativas: [
      'Não garante meios eficazes para o armazenamento dos produtos para diagnóstico in vitro e do material biológico.',
      'Não possui sistema para garantir as condições de armazenamento em caso de falha de fornecimento de energia elétrica.',
      'Não possui as informações sobre as condições de armazenamento de todos os produtos.',
      'Garante meios eficazes para o armazenamento dos produtos para diagnóstico in vitro e do material biológico, garantindo sua conservação, eficácia e segurança, mesmo diante de falha de fornecimento de energia elétrica.',
      'Possui relação nominal de todas as especificações de armazenamento de todos os produtos armazenados.',
      'Possui protocolo para verificação periódica das condições de armazenamento.',
    ],
  },
  {
    numero: 25,
    indicador: 'Controle de Temperatura',
    criticidade: 'C',
    baseLegal: 'Art. 63 da RDC 786/2023',
    alternativas: [
      'Não realiza as medições das temperaturas dos instrumentos que necessitam funcionar com controle de temperatura.',
      'Realiza medições das temperaturas dos instrumentos que necessitam funcionar com temperatura controlada, porém os registros no início e no fim da operação estão incompletos.',
      'Realiza medições das temperaturas dos instrumentos que necessitam funcionar com temperatura controlada e registra no início e no fim da operação. Porém, com relação aos instrumentos de operação contínua, o registro não monitora a operação do instrumento durante todo o processo.',
      'Realiza medições das temperaturas dos instrumentos que necessitam funcionar com temperatura controlada e registra no início e no fim da operação. Para os instrumentos de operação contínua, o registro é realizado de forma a monitorar a operação do instrumento durante todo o processo.',
      'Monitora e registra eletronicamente, em tempo real, a temperatura.',
      'Possui sistema de alerta para variações de temperatura fora das tolerâncias.',
    ],
  },
  {
    numero: 26,
    indicador: 'Produtos para Diagnóstico in vitro, Reagentes e Insumos',
    criticidade: 'C',
    baseLegal: 'Artigos 64, 65 e 66 da RDC 786/2023',
    alternativas: [
      'Não dispõe dos instrumentos necessários de acordo com sua complexidade e demanda de atendimento.',
      'Dispõe de instrumentos de acordo com sua complexidade e demanda de atendimento, porém não mantém instruções escritas em português referentes aos instrumentos ou manual do fabricante. Ou não registra o recebimento dos produtos para diagnóstico de uso in vitro, reagentes e insumos.',
      'Os registros do recebimento dos produtos para diagnóstico de uso in vitro, reagentes e insumos não possuem informações completas (lote, conformidade das condições de transporte, data de recebimento) para garantir sua rastreabilidade e qualidade.',
      'O serviço dispõe de instrumentos de acordo com sua complexidade e demanda de atendimento. Mantém instruções escritas em português referentes aos instrumentos ou manual do fabricante. Registra o recebimento dos produtos para diagnóstico de uso in vitro, reagentes e insumos contendo número de lote, conformidade das condições de transporte, data de recebimento e outras informações para garantir sua rastreabilidade e qualidade.',
      'Possui sistema eletrônico de registro.',
      'Possui sistema eletrônico de registro, com alerta.',
    ],
  },
  {
    numero: 27,
    indicador: 'Rotulagem do Reagente e Insumo Fracionados',
    criticidade: 'C',
    baseLegal: 'Art. 67 da RDC 786/2023',
    alternativas: [
      'Comercializa os reagentes e/ou insumos fracionados ou preparados pelo serviço. E/ou não há rotulagem.',
      'Foram encontrados reagentes e/ou insumos com rótulos contendo informações não legíveis.',
      'O reagente e insumo fracionados ou preparados pelo serviço e por ele utilizados são identificados com rótulo, porém com informações incompletas.',
      'O reagente e insumo fracionados ou preparados pelo serviço e por ele utilizados são identificados com rótulo contendo: I- nome do reagente ou insumo; II- concentração ou especificação; III- número do lote, quando aplicável; IV- data de preparação; V- nome do responsável pelo fracionamento ou preparo; VI- data de validade; VII- condições de armazenamento; e VIII- informações referentes a riscos potenciais.',
      'Além das informações no rótulo, possui código de barra para identificação, gerenciamento e rastreamento.',
      'Realiza auditoria periódica para verificação do cumprimento dos requisitos de rotulagem.',
    ],
  },
  {
    numero: 28,
    indicador: 'Sistema de Informação',
    criticidade: 'C',
    baseLegal: 'Artigos 32, 71 e 72 da RDC 786/2023',
    alternativas: [
      'Não possui sistema de informação.',
      'Não realiza avaliação e verificação do sistema ou programa de informática antes de sua implementação.',
      'Define uma política e responsabilidades, mas estão incompletas ou desatualizadas.',
      'Define uma política e responsabilidades para estabelecer: I- sistemática de acesso a dados e informações dos pacientes e dos profissionais do serviço; II- controle de acesso a lançamento e alterações de dados e resultados dos exames de pacientes, contendo históricos com datas, horários, usuário e local em que ocorreu o cadastro ou alteração das informações; III- processo sistematizado para liberação de resultados dos exames e laudos de pacientes, automática ou manual; IV- política de privacidade e confidencialidade da informação; e V- sistemática definida e documentada de proteção contra acessos não autorizados. Avalia e verifica o sistema ou programa de informática antes de sua implementação e documenta com as informações referentes à disponibilidade, confiabilidade, integridade dos dados e responsabilidades das instituições e usuários.',
      'Utiliza sistema de informação computadorizado.',
      'Possui protocolo de validação do sistema de informação utilizado.',
    ],
  },
  {
    numero: 29,
    indicador: 'Biossegurança',
    criticidade: 'NC',
    baseLegal: 'Art. 76 da RDC 786/2023',
    alternativas: [
      'Não dispõe de instruções escritas de biossegurança.',
      'Dispõe de instruções escritas de biossegurança, porém estão desatualizadas ou não contemplam todos os IV itens.',
      'Mantém atualizadas as instruções escritas de biossegurança contemplando os IV itens, porém não estão disponíveis a todos os funcionários.',
      'Mantém atualizadas as instruções escritas de biossegurança e disponibilizadas a todos os funcionários, contemplando, no mínimo: I- instruções escritas de biossegurança biológica, química, física, ocupacional e ambiental, de acordo com os procedimentos realizados, instrumentos e microrganismos envolvidos, adotando as medidas compatíveis; II- instruções de uso para EPI e EPC; III- procedimentos em casos de acidentes; e IV- manuseio e transporte de material biológico, quando aplicável.',
      'Realiza, periodicamente, simulações dos possíveis casos relacionados à biossegurança.',
      'Implanta ações de biossegurança, para além das Normas Sanitárias, utilizando publicações reconhecidas nacional ou internacionalmente.',
    ],
  },
  {
    numero: 30,
    indicador: 'Higienização',
    criticidade: 'C',
    baseLegal: 'Artigos 78 e 79 da RDC 786/2023',
    alternativas: [
      'Não possui instruções escritas para limpeza, desinfecção e esterilização das superfícies, instalações, artigos e materiais.',
      'Possui instruções escritas para limpeza, desinfecção e esterilização das superfícies, instalações, artigos e materiais, no entanto, há sujidade nos ambientes.',
      'Possui instruções escritas para limpeza, desinfecção e esterilização das superfícies, instalações, artigos e materiais, porém a limpeza do ambiente onde é realizado o EAC não é registrada diariamente no início e no término do horário de funcionamento.',
      'Possui instruções escritas para limpeza, desinfecção e esterilização das superfícies, instalações, artigos e materiais. Assegura a higienização dos ambientes de forma a garantir a segurança do paciente e dos profissionais. A limpeza do ambiente onde é realizado o EAC tem sua execução registrada diariamente no início e no término do horário de funcionamento.',
      'Realiza a limpeza do ambiente onde é realizado o EAC, em outros horários além do início e no término do horário de funcionamento.',
      'Possui rotina de supervisão diária da higienização.',
    ],
  },
  {
    numero: 31,
    indicador: 'Saneantes',
    criticidade: 'C',
    baseLegal: 'Art. 80 da RDC 786/2023',
    alternativas: [
      'Saneantes e/ou produtos usados nos processos de limpeza e desinfecção não estão regularizados junto à Anvisa.',
      'Foi encontrado algum saneante ou produto sem regularização junto à Anvisa ou são diluídos/fracionados sem identificação.',
      'Produtos e/ou saneantes utilizados nos processos de limpeza e desinfecção estão regularizados junto à Anvisa, porém seu uso não segue as especificações dos fabricantes.',
      'Os saneantes e os produtos usados nos processos de limpeza e desinfecção estão regularizados junto à Anvisa e são utilizados segundo as especificações do fabricante.',
      'Possui sistema automatizado para diluição.',
      'Possui sistema automatizado para diluição e registro com rastreabilidade de cada lote.',
    ],
  },
  {
    numero: 32,
    indicador: 'Procedimentos documentados que orientam as atividades dos serviços que executam EAC',
    criticidade: 'C',
    baseLegal: 'Art. 85 da RDC 786/2023',
    alternativas: [
      'Não possui procedimentos documentados.',
      'Não disponibiliza nos locais de execução.',
      'Os procedimentos documentados estão incompletos ou desatualizados.',
      'Disponibiliza nos locais de execução do exame, procedimentos documentados orientando com relação às suas atividades, incluindo: I- sistemática de registro e liberação de resultados; II- procedimentos para resultados potencialmente críticos; e III- sistemática de revisão de resultados e liberação de laudos por profissional legalmente habilitado.',
      'Revisa anualmente os procedimentos ou após modificações das atividades.',
      'Realiza auditorias periódicas nas práticas dos procedimentos.',
    ],
  },
  {
    numero: 33,
    indicador: 'Rastreabilidade do Material Biológico',
    criticidade: 'C',
    baseLegal: 'Art. 94 da RDC 786/2023',
    alternativas: [
      'Não garante a rastreabilidade.',
      'Os registros não possibilitam a rastreabilidade completa.',
      'Realiza todos os registros, mas de forma que dificulta a rastreabilidade completa.',
      'Garante e evidencia a rastreabilidade de todas as atividades relacionadas ao material biológico, desde sua coleta até o seu descarte.',
      'Possui sistema de dupla verificação.',
      'Existe processo de gerenciamento da rastreabilidade.',
    ],
  },
  {
    numero: 34,
    indicador: 'Rastreabilidade',
    criticidade: 'C',
    baseLegal: 'Artigos 56, 66, 96, 97, Inciso II do art. 123 e Inciso II do art. 130 da RDC 786/2023',
    alternativas: [
      'O serviço que executa EAC não dispõe de meios que permitem a rastreabilidade.',
      'Os registros não possibilitam a rastreabilidade completa.',
      'Realiza todos os registros, mas de forma que dificulta a rastreabilidade completa.',
      'O serviço que executa EAC dispõe de meios que permitem a rastreabilidade de toda a fase analítica.',
      'Possui sistema de dupla verificação.',
      'Existe processo de gerenciamento da rastreabilidade.',
    ],
  },
  {
    numero: 35,
    indicador: 'Orientações Fase Pré-Analítica',
    criticidade: 'NC',
    baseLegal: 'Art. 98 da RDC 786/2023',
    alternativas: [
      'Não disponibiliza ao paciente ou responsável instruções sobre o preparo e coleta de material, ou não solicita documento válido com foto para comprovar sua identificação.',
      'Disponibiliza informações não completas aos pacientes e/ou responsável.',
      'Disponibiliza ao paciente ou responsável instruções (físicas, digitais ou verbais) orientando sobre o preparo e coleta de material biológico, porém a linguagem utilizada é complexa e dificulta a compreensão pelo paciente.',
      'Disponibiliza ao paciente ou responsável instruções (físicas, digitais ou verbais), em linguagem acessível, orientando sobre o preparo e coleta de material biológico, tendo como objetivo a compreensão do paciente; e solicita ao paciente documento válido com foto que comprove a sua identificação. Para pacientes em atendimento de urgência/internação, a comprovação dos dados pode ser obtida no prontuário.',
      'Informa ao paciente e/ou responsável, por mais de um meio de comunicação.',
      'Registra a ciência do paciente e/ou responsável.',
    ],
  },
  {
    numero: 36,
    indicador: 'Cadastro de Paciente',
    criticidade: 'C',
    baseLegal: 'Artigos 99 e 100 da RDC 786/2023',
    alternativas: [
      'Todos os cadastros possuem informações incompletas.',
      'Alguns cadastros estão com as informações incompletas.',
      'Cadastros com informações inconsistentes.',
      'O serviço é responsável pelo cadastro do paciente, que inclui as seguintes informações: I- número do registro de identificação do paciente; II- nome completo; III- nome social, quando aplicável; IV- data de nascimento; V- sexo biológico; VI- nome da mãe; VII- telefone ou endereço do paciente; e VIII- nome e contato do responsável em caso de menor de idade ou de incapaz.',
      'Possui cadastro com informações complementares do paciente, úteis aos exames, a exemplo de alergia.',
      'Registra confirmação do paciente nas informações cadastradas.',
    ],
  },
  {
    numero: 37,
    indicador: 'Cadastro do EAC',
    criticidade: 'C',
    baseLegal: 'Artigos 101 e 102 da RDC 786/2023',
    alternativas: [
      'O serviço que executa o EAC não realiza o cadastro do exame.',
      'Realiza o cadastro sem todas as informações.',
      'Cadastros com informações inconsistentes.',
      'Serviço que executa EAC é responsável pelo cadastro do exame, incluindo: I- nome do solicitante; II- data e horário do atendimento; III- horário da coleta do material biológico, quando aplicável; IV- nome e número do cadastro CNES da unidade responsável pela coleta; V- exames solicitados e tipo do material biológico; VI- informações adicionais; VII- nome do profissional que executou o exame; VIII- nome do profissional que executou a coleta do material biológico, quando aplicável; IX- nome do profissional que validou o recebimento do material biológico, quando aplicável; X- data prevista para entrega do laudo, quando aplicável; XI- indicação de urgência, quando aplicável; e XII- informações adicionais do paciente relevantes para o EAC, como uso de medicamentos, vitaminas e condições de saúde.',
      'Realiza, periodicamente, supervisão in loco dos procedimentos de cadastro do EAC.',
      'Possui dupla verificação das informações cadastradas.',
    ],
  },
  {
    numero: 38,
    indicador: 'Comprovante de Atendimento',
    criticidade: 'NC',
    baseLegal: 'Art. 103 da RDC 786/2023',
    alternativas: [
      'Não fornece comprovante de atendimento.',
      'Fornece ao paciente ou ao seu responsável um comprovante de atendimento com informações incompletas ou inconsistentes.',
      'Fornece ao paciente ou ao seu responsável um comprovante de atendimento com informações ilegíveis.',
      'Fornece ao paciente ou ao seu responsável um comprovante de atendimento contendo: I- número do registro; II- nome do paciente; III- data do atendimento; IV- data prevista de entrega do laudo; V- relação de exames solicitados; e VI- dados do contato do serviço que executa o EAC. Obs.: O comprovante pode ser dispensado nos casos de EAC cuja execução ocorra no ato da coleta, mediante a entrega de laudo.',
      'Fornece ao paciente ou ao seu responsável o comprovante de atendimento em meio físico e digital.',
      'Disponibiliza aplicativo com todas as informações.',
    ],
  },
  {
    numero: 39,
    indicador: 'Identificação do Material Biológico',
    criticidade: 'C',
    baseLegal: 'Art. 104 da RDC 786/2023',
    alternativas: [
      'Material biológico não é identificado no ato da coleta ou do recebimento.',
      'Material biológico é identificado no ato da coleta ou do recebimento, porém não contém todas as informações.',
      'Material biológico é identificado no ato da coleta ou do recebimento, contém todas as informações, porém há rasura.',
      'O material biológico é identificado no ato da coleta ou do recebimento, contendo, no mínimo: I- nome do paciente; II- data de nascimento ou idade; III- tipo do material biológico; e IV- data e horário da coleta.',
      'Além das informações de identificação, possui código de barra para rastreamento.',
      'Realiza supervisão periódica para verificação da identificação do material biológico.',
    ],
  },
  {
    numero: 40,
    indicador: 'Definição de Critérios',
    criticidade: 'C',
    baseLegal: 'Art. 105 da RDC 786/2023',
    alternativas: [
      'O serviço não define os critérios para aceitação, rejeição, identificação e realização de EAC em material biológico com restrições.',
      'Possui critérios definidos, mas não estão compatíveis com os exames realizados.',
      'Possui critérios definidos, mas não possui práticas de verificação.',
      'O serviço que executa EAC define os critérios para aceitação, rejeição, identificação e realização de EAC em material biológico com restrições.',
      'Os critérios são estabelecidos conforme protocolos nacionais/internacionais.',
      'Registra, avalia e implanta ações corretivas nos casos identificados de aceitação indevida de material.',
    ],
  },
  {
    numero: 41,
    indicador: 'Transporte do Material Biológico',
    criticidade: 'C',
    baseLegal: 'Art. 13, 107, 108 e 110 da RDC 786/2023',
    alternativas: [
      'Material biológico transportado sem informações.',
      'Material biológico transportado com informações rasuradas.',
      'Material biológico transportado com informações incompletas.',
      'Todo material biológico transportado contém, em sua embalagem terciária, dados dos exames solicitados, do material biológico coletado, do paciente e do solicitante.',
      'Possui registro e rastreabilidade de todo material biológico transportado.',
      'Possui registro e rastreabilidade de todo material biológico transportado, com monitoramento georreferenciado em tempo real.',
    ],
  },
  {
    numero: 42,
    indicador: 'Instruções Escritas',
    criticidade: 'NC',
    baseLegal: 'Inciso I do art. 123 da RDC 786/2023',
    alternativas: [
      'O serviço que executa EAC não dispõe de instruções escritas para todos os processos analíticos.',
      'Possui instruções escritas para todos os processos analíticos, porém não estão atualizadas.',
      'Possui instruções escritas para todos os processos analíticos, estão atualizadas, porém não estão disponíveis.',
      'O serviço que executa EAC dispõe de instruções escritas, disponíveis e atualizadas para todos os processos analíticos, podendo utilizar as instruções de uso do fabricante.',
      'Possui controle de versão das instruções, com rastreabilidade.',
      'Avalia sistematicamente as instruções, com ações de melhoria.',
    ],
  },
  {
    numero: 43,
    indicador: 'Definição de Limites de Risco, Valores Críticos e Alertas',
    criticidade: 'C',
    baseLegal: 'Inciso III do art. 123 da RDC 786/2023',
    alternativas: [
      'Não define limites de Risco, Valores Críticos e Alertas.',
      'Para alguns exames com resultados que necessitam de tomada imediata de decisão, não define limites de Risco, Valores Críticos e Alertas.',
      'Define limites de Risco, Valores Críticos e Alertas, mas não define o fluxo de comunicação.',
      'O serviço que executa EAC define limites de risco, valores críticos ou de alerta, para os exames com resultados que necessitam de tomada imediata de decisão, bem como define fluxo de comunicação ao profissional de saúde responsável ou paciente quando for necessário decisão imediata.',
      'Sistema de alerta informatizado, identificando em tempo real os resultados dos exames.',
      'Avalia sistematicamente os resultados dos exames, verificando a efetividade dos alertas, implantando ações de melhoria.',
    ],
  },
  {
    numero: 44,
    indicador: 'Pureza da Água',
    criticidade: 'C',
    baseLegal: 'Incisos IV e V do art. 123 da RDC 786/2023',
    alternativas: [
      'Não define o grau de pureza da água reagente.',
      'Define o grau de pureza da água reagente, porém não implementa as avaliações e testes necessários para assegurar a conformidade.',
      'Define o grau de pureza da água reagente, porém não realiza as avaliações e testes necessários para assegurar a conformidade, na periodicidade definida.',
      'O serviço que executa EAC, quando aplicável, define o grau de pureza da água reagente utilizada na realização de exames e nos controles de qualidade e implementa as avaliações e testes necessários para assegurar a conformidade do grau de pureza da água reagente.',
      'Utiliza apenas água reagente disponível comercialmente.',
      'Utiliza apenas água reagente disponível comercialmente, realizando controle de qualidade por lote.',
    ],
  },
  {
    numero: 45,
    indicador: 'Laboratório de Apoio (quando aplicável)',
    criticidade: 'C',
    baseLegal: 'Artigos 125 e 126 da RDC 786/2023',
    alternativas: [
      'Não possui contrato ou não avalia a qualidade dos serviços prestados.',
      'Não avalia todos os serviços prestados.',
      'Avalia todos os serviços prestados, mas em periodicidade superior a um ano.',
      'O Serviço possui formalizada a prestação de serviços através de contratos e avalia anualmente a qualidade dos serviços prestados pelo Laboratório de Apoio.',
      'O contrato de prestação de serviço é renovado e revisado anualmente.',
      'Avalia, em periodicidade menor que anual, a qualidade dos serviços prestados pelo Laboratório de Apoio.',
    ],
  },
  {
    numero: 46,
    indicador: 'Metodologia Própria',
    criticidade: 'C',
    baseLegal: 'Artigos 129, 130, 131, 132, 133 e 134 da RDC 786/2023',
    alternativas: [
      'Comercializa, repassa, doa ou entrega para consumo reagentes ou qualquer produto proveniente de Metodologia Própria (não se aplica à disponibilização de reagentes e materiais para uso na fase pré-analítica pelo Serviço Tipo II vinculado).',
      'Utiliza metodologia própria, porém não está completamente documentada.',
      'Não especifica no laudo quais resultados foram obtidos por Metodologia Própria.',
      'Utiliza metodologia própria documentada contendo: I- descrição das etapas do processo; II- rastreabilidade de todos os produtos e insumos utilizados; III- especificação e sistemática de aprovação de insumos, reagentes, equipamentos e instrumentos; IV- sistemática de validação de etapas e procedimentos, volume de reagentes, tipos de material biológico, materiais necessários, forma de interpretação e resultados; e V- determinação da sensibilidade e especificidade das metodologias. Especifica no laudo quais resultados foram obtidos por Metodologia Própria.',
      'Realiza avaliação e revisão sistemática, implantando e validando melhorias.',
      'Valida, com auditoria externa, todas as metodologias próprias utilizadas.',
    ],
  },
  {
    numero: 47,
    indicador: 'Relatório de Validação (metodologia própria)',
    criticidade: 'C',
    baseLegal: 'Art. 135 da RDC 786/2023',
    alternativas: [
      'Não elabora relatório de validação.',
      'Elabora relatório de validação com descrição dos procedimentos, materiais necessários e utilizados, parâmetros analíticos, critérios de aceitação e resultados, porém com detalhamento insuficiente para sua reprodução.',
      'Elabora relatório de validação com descrição dos procedimentos, materiais necessários e utilizados, parâmetros analíticos, critérios de aceitação e resultados, com detalhamento que possibilita sua reprodução, porém sem avaliação estatística, mesmo quando aplicável.',
      'Elabora relatório de validação com descrição dos procedimentos, materiais necessários e utilizados, parâmetros analíticos, critérios de aceitação e resultados, com detalhamento que possibilita sua reprodução e, quando aplicável, sua avaliação estatística.',
      'Possui protocolo de reavaliação periódica das validações.',
      'Relatório de validação possui avaliação de auditor externo.',
    ],
  },
  {
    numero: 48,
    indicador: 'Instruções Escritas para Liberação de Resultados',
    criticidade: 'NC',
    baseLegal: 'Art. 136 da RDC 786/2023',
    alternativas: [
      'Não possui instruções escritas para liberação dos resultados ou assinatura legalmente válida dos laudos.',
      'Possui instruções escritas para liberação dos resultados e assinatura válida dos laudos, porém contempla apenas as situações de rotina.',
      'As instruções escritas não estão atualizadas.',
      'Possui instruções escritas para liberação dos resultados e assinatura legalmente válida dos laudos, contemplando as situações de rotina, plantões, urgências e emergências.',
      'Possui controle de versão das instruções, com rastreabilidade.',
      'Avalia sistematicamente as instruções, com ações de melhoria.',
    ],
  },
  {
    numero: 49,
    indicador: 'Laudo',
    criticidade: 'C',
    baseLegal: 'Artigos 137 e 138 da RDC 786/2023',
    alternativas: [
      'Laudo ilegível ou escrito em língua distinta do português ou não possui assinatura de profissional de nível superior legalmente habilitado.',
      'O laudo é legível, sem rasuras de transcrição, escrito em língua portuguesa, assinado por profissional de nível superior legalmente habilitado, porém não contém todas as informações obrigatórias.',
      'Utiliza assinatura digital, sem validade legal.',
      'O laudo é legível, sem rasuras de transcrição, escrito em língua portuguesa, assinado por profissional de nível superior legalmente habilitado e contém, no mínimo: I- nome do serviço que executa EAC responsável pela análise, com nº do CNES; II- endereço e telefone de contato do Serviço que executa EAC responsável pela análise; III- nome e número do registro do RT, no conselho de classe; IV- nome e número do registro no conselho de classe do profissional legalmente habilitado que assina o laudo do exame; V- nome e registro de identificação do paciente; VI- idade ou data de nascimento; VII- data da coleta do material biológico; VIII- nome do exame, tipo de material biológico e método analítico; IX- resultado do exame e unidade de medição; X- valores de referência, limitações técnicas da metodologia e dados para interpretação; XI- especificação de metodologia própria, quando aplicável; XII- quando aceito material biológico com restrição, essa condição consta no laudo; XIII- data de emissão do laudo; e XIV- assinatura legalmente válida.',
      'Laudo apresenta valores históricos possibilitando acompanhamento dos exames realizados.',
      'Avalia periodicamente os laudos, implantando melhorias na apresentação dos resultados.',
    ],
  },
  {
    numero: 50,
    indicador: 'Transcrição de Laudos',
    criticidade: 'C',
    baseLegal: 'Art. 139 da RDC 786/2023',
    alternativas: [
      'Não garante a fidedignidade na transcrição dos laudos emitidos pelo Laboratório de Apoio.',
      'Garante a fidedignidade na transcrição dos laudos, mas não informa o nome do Laboratório de Apoio.',
      'Garante a fidedignidade na transcrição dos laudos, porém inclui comentários sem informar que não são do Laboratório de Apoio.',
      'Caso opte pela transcrição dos laudos emitidos pelo Laboratório de Apoio, o Serviço de EAC garante a fidedignidade dos mesmos, podendo adicionar comentários de interpretação ao texto do Laboratório de Apoio, considerando o estado do paciente e o contexto global dos exames. O laudo contém o nome do Laboratório de Apoio que realizou o exame.',
      'Possui dupla verificação das transcrições.',
      'Possui sistema informatizado para transmissão direta entre os sistemas, dos resultados, minimizando a possibilidade de erro.',
    ],
  },
  {
    numero: 51,
    indicador: 'Gestão do Controle da Qualidade (GCQ)',
    criticidade: 'C',
    baseLegal: 'Artigos 141, 142, 143, 144 e 145 da RDC 786/2023',
    alternativas: [
      'Não realiza CIQ e CEQ.',
      'Realiza CIQ ou CEQ, porém os registros dos controles de qualidade ou as instruções escritas para sua realização estão indisponíveis.',
      'Realiza CIQ e CEQ, mantém os registros dos controles de qualidade, bem como das instruções escritas para sua realização. Porém os registros estão incompletos.',
      'O serviço realiza Controle Interno de Qualidade e Controle Externo da Qualidade. Mantém os registros dos controles de qualidade, bem como das instruções escritas para sua realização. Os registros contemplam: I- lista de todos os exames realizados; II- forma de controle e frequência de utilização; III- limites e critérios de aceitabilidade para os resultados dos controles; e IV- avaliação e registro dos resultados dos controles.',
      'Utiliza sistema informatizado, com representação gráfica e unificada de todos os resultados, possibilitando avaliações mais rápidas.',
      'Possui sistema de alerta para variações fora das tolerâncias de todos os parâmetros.',
    ],
  },
  {
    numero: 52,
    indicador: 'Controle Interno da Qualidade (CIQ)',
    criticidade: 'C',
    baseLegal: 'Art. 147 da RDC 786/2023',
    alternativas: [
      'Não realiza CIQ.',
      'Realiza CIQ para alguns analitos.',
      'Realiza CIQ para todos os analitos executados, porém não contempla todos os V tópicos.',
      'Realiza CIQ para todos os analitos executados e contempla: I- monitoramento da fase analítica pela análise da amostra de controle, com registro do resultado obtido e análise de dados; II- definição dos critérios de aceitação e rejeição dos resultados por tipo de analito e de acordo com a metodologia utilizada; III- liberação ou rejeição das análises após validação dos resultados das amostras de controle; IV- registro das inadequações, investigação de causas e ações tomadas para os resultados rejeitados de amostras de controle; e V- critério de avaliação dos resultados das amostras de controle.',
      'Utiliza sistema informatizado, com representação gráfica e unificada de todos os resultados.',
      'Possui sistema de alerta para variações fora das tolerâncias de todos os parâmetros.',
    ],
  },
  {
    numero: 53,
    indicador: 'Amostras de Controle',
    criticidade: 'C',
    baseLegal: 'Art. 148 da RDC 786/2023',
    alternativas: [
      'Utiliza amostras de controle comerciais não regularizadas junto à Anvisa ou não dispõe de amostras de controle.',
      'Utiliza amostras de controle comerciais, regularizadas junto à Anvisa, ou amostras controle comerciais obtidas por comparação interlaboratorial, porém as amostras controle são analisadas de forma diferente das amostras dos pacientes.',
      'Utiliza formas alternativas, descritas na literatura científica, porém não avaliam a precisão do sistema analítico.',
      'Utiliza amostras de controle comerciais, regularizadas junto à Anvisa, ou amostras controle comerciais obtidas por comparação interlaboratorial. As amostras controle são analisadas da mesma forma que as amostras dos pacientes. Caso utilize formas alternativas descritas na literatura científica, essas devem permitir a avaliação da precisão do sistema analítico.',
      'Realiza qualificação periódica dos fornecedores de amostra.',
      'Participa de dois programas de controle da qualidade.',
    ],
  },
  {
    numero: 54,
    indicador: 'Controle Interno da Qualidade dos Instrumentos',
    criticidade: 'C',
    baseLegal: 'Art. 149 da RDC 786/2023',
    alternativas: [
      'Não realiza CIQ em nenhum dos instrumentos em uso.',
      'Realiza CIQ em alguns dos instrumentos em uso.',
      'Realiza CIQ em todos os instrumentos em uso, mas não segue periodicidade definida.',
      'Realiza CIQ em todos os instrumentos em uso.',
      'Utiliza sistema informatizado, com representação gráfica e unificada de todos os resultados.',
      'Possui sistema de alerta para variações fora das tolerâncias de todos os parâmetros.',
    ],
  },
  {
    numero: 55,
    indicador: 'CIQ para produtos de diagnóstico in vitro de leitura direta',
    criticidade: 'C',
    baseLegal: 'Art. 150 da RDC 786/2023',
    alternativas: [
      'Não realiza CIQ dos produtos de diagnóstico in vitro de leitura direta.',
      'Realiza CIQ apenas a cada troca de lote ou a cada remessa.',
      'Realiza para cada troca de lote e cada remessa, mas os registros não estão completos.',
      'Realiza CIQ, no mínimo, a cada troca de lote e a cada remessa dos produtos para diagnóstico in vitro que não necessitam de instrumento para leitura, interpretação ou visualização do resultado.',
      'Realiza mais de um teste para cada lote ou remessa.',
      'Realiza teste para cada lote ou remessa, por quantidade ou tempo definidos.',
    ],
  },
  {
    numero: 56,
    indicador: 'Controle Externo da Qualidade (CEQ)',
    criticidade: 'C',
    baseLegal: 'Artigos 151, 152 e 153 da RDC 786/2023',
    alternativas: [
      'Não participa ou não realiza os controles externos de qualidade.',
      'Participa de CEQ, porém não contempla todos os instrumentos em uso ou não contempla todos os exames nem por formas alternativas.',
      'O Serviço participa de CEQ contemplando todos os instrumentos em uso. No entanto, não participa anualmente de todos os ensaios de proficiência, disponibilizados pelos provedores de ensaio de proficiência e fornecedores.',
      'O Serviço participa de CEQ, contemplando todos os instrumentos em uso. Para os exames não contemplados no CEQ, o serviço utiliza formas alternativas descritas em literatura científica, para avaliação da exatidão do sistema analítico. O serviço participa anualmente de todos os ensaios de proficiência, disponibilizados pelos provedores de ensaio de proficiência e fornecedores.',
      'Participa de CEQ em periodicidade menor que um ano.',
      'Participa de CEQ em periodicidade anual, mas com limites de tolerância mais restritos que os recomendados.',
    ],
  },
];
