import type { RoiIndicador } from './roteiro-roi-radiologia';

/**
 * ROI — Roteiro Objetivo de Inspeção da ANVISA: SERVIÇO DE ODONTOLOGIA
 * (versão 1.2, 30/08/2026), baseado na RDC nº 1.002/2025.
 *
 * Mesma estrutura do ROI de Radiografia Médica (roteiro-roi-radiologia.ts):
 * 51 indicadores avaliados numa escala de 0 a 5 (NOTA_CONFORME = 3), em vez
 * de SIM/NÃO/ND. Conteúdo extraído do PDF oficial anexado (Roteiro Objetivo
 * de Inspeção Odontologia Versão 1.2.pdf) — não editar à mão sem conferir com
 * o PDF: os textos são a redação legal usada como fundamentação no relatório.
 */
export const ROI_ODONTOLOGIA: RoiIndicador[] = [
  {
    numero: 1,
    indicador: 'Licença Sanitária',
    criticidade: 'NC',
    baseLegal: 'Art. 8º da RDC 1002/2025 e art. 10 da RDC 63/2011',
    alternativas: [
      'Não possui licença sanitária.',
      'Licença sanitária vencida, sem pedido de renovação.',
      'Licença sanitária vencida, com pedido de renovação ou serviço em processo inicial de licenciamento ou a licença não está afixada em local visível ao público.',
      'Possui licença sanitária atualizada, concedida pela autoridade sanitária competente e afixada em local visível ao público.',
      'Realizou pedido de renovação antes do vencimento da Licença sanitária.',
      'Licença sanitária atualizada, com pedido de renovação e autoinspeção realizada com o ROI de Odontologia.',
    ],
  },
  {
    numero: 2,
    indicador: 'Responsável Técnico (RT)',
    criticidade: 'NC',
    baseLegal: 'Arts. 5º e 7º da RDC 1002/2025',
    alternativas: [
      'Não dispõe de RT designado junto ao órgão sanitário competente.',
      'Responsável Técnico ou substituto difere do designado junto ao órgão sanitário competente.',
      'Dispõe de RT, porém apesar de possuir mais de um cirurgião-dentista, não possui RT substituto.',
      'Dispõe de profissional cirurgião-dentista, legalmente habilitado, designado como Responsável Técnico (RT). Caso exista mais de um cirurgião-dentista, dispõe de RT substituto.',
      'RT ou substituto possui pós graduação na área.',
      'RT ou substituto está presente durante todo o período de funcionamento.',
    ],
  },
  {
    numero: 3,
    indicador: 'Série de Documentos de Boas Práticas de Funcionamento (SDBPF)',
    criticidade: 'NC',
    baseLegal: 'Arts. 110 e 111 da RDC 1002/2025',
    alternativas: [
      'Não possui nenhum dos documentos e requisitos que devem compor a SDBPF.',
      'A SDBPF não está formalmente aprovada, está em elaboração ou não está completa.',
      'A SDBPF não está atualizada ou não está disponível para todos os membros da equipe.',
      'O serviço possui implementada a Série de Documentos de Boas Práticas de Funcionamento (SDBPF) que: I - Está acessível para consulta por todos os profissionais do serviço de saúde e autoridades sanitárias, sempre que solicitado; II - Está adaptada à realidade do serviço e alinhada aos documentos técnicos e regulamentos publicados pela Anvisa; III - Está formalmente aprovada e assinada pelo responsável legal do serviço de saúde; IV - Tem seus planos, protocolos e procedimentos operacionais padrão revisados, no mínimo a cada 2 anos, quando aplicável, ou sempre que houver mudança no perfil epidemiológico do serviço, tipo de assistência prestada ou procedimentos assistenciais realizados. A SDBPF contém instruções sequenciais dos procedimentos realizados no serviço para utilização dos profissionais que realizam atividades de recepção dos pacientes, procedimentos de limpeza, desinfecção e esterilização de instrumentais, artigos, equipamentos e superfícies, manutenção, entre outros serviços.',
      'A SDBP está disponível em meio eletrônico.',
      'A SDBP é revisada anualmente, com registro das ações de melhoria implantadas.',
    ],
  },
  {
    numero: 4,
    indicador: 'Série de Documentos de Boas Práticas de Funcionamento (SDBPF) - Conteúdo',
    criticidade: 'NC',
    baseLegal: 'Art. 113 da RDC 1002/2025',
    alternativas: [
      'O conteúdo dos documentos constantes na SDBP não são compatíveis com as atividades ou natureza jurídica do serviço.',
      'Não possui alguns dos 16 itens definidos como obrigatórios ou alguns dos itens estão incompletos.',
      'A SDBP possui documentos desatualizados ou foi identificado algum documento faltando.',
      'A SDBP está adequada à realidade e assistência prestada no serviço e contém: I - PBA aprovado pela vigilância sanitária; II - Gestão de Recursos Humanos com a descrição de cargos e funções, fichas funcionais atualizadas, comprovação de formação profissional, controle de saúde ocupacional e capacitações obrigatórias; III - Plano anual de educação permanente, com registros das capacitações realizadas; IV - Contratos, com licenças e qualificações dos serviços terceirizados; V - Plano de Monitoramento e Controle da Água, com registros; VI - Controle de vetores e pragas urbanas; VII - Plano Anual de Manutenção preventiva e corretiva da edificação e instalações, com registros; VIII - Plano de Gerenciamento de Tecnologias em Saúde-PGTS; IX - Plano de Gerenciamento de Resíduos de Serviços de Saúde-PGRSS; X - Protocolo e Procedimento Operacional Padrão para processamento dos Dispositivos Médicos, incluindo rastreabilidade; XI - Protocolo de Limpeza de ambiente e desinfecção de superfícies, ambientes e equipamentos; XII - Plano de Segurança do Paciente - PSP, nos termos do art. 119; XIII - Protocolo de higiene das mãos, precauções e isolamento; XIV - Protocolo de encaminhamento do profissional, em caso de acidentes; XV - Protocolo de atendimento e encaminhamento dos pacientes em caso de urgências e emergências; XVI - Plano de prevenção e controle de infecções - PP-IRAS.',
      'Além da documentação mínima, a SDBP contempla outros documentos complementares a exemplo de Protocolo de devolução de imagens e materiais ou outros não previstos em legislação.',
      'O Conteúdo da SDBP é revisado anualmente, com registro das ações de melhoria implantadas.',
    ],
  },
  {
    numero: 5,
    indicador: 'Capacitação',
    criticidade: 'NC',
    baseLegal: 'Art. 114 da RDC 1002/2025; Arts. 32 e 33 da RDC 63/2011',
    alternativas: [
      'Não realiza a capacitação dos profissionais.',
      'Não realiza a capacitação para todos os profissionais.',
      'A capacitação é realizada de forma incompleta, sem periodicidade definida ou sem os devidos registros.',
      'Todos os profissionais do serviço que prestam assistência odontológica possuem capacitação admissional e periódica sobre rotinas, protocolos técnicos padronizados, POP, definidos na SDBPF. As capacitações são registradas contendo, no mínimo, data, horário, carga horária, conteúdo ministrado, identificação e qualificação do instrutor e dos profissionais participantes.',
      'Realiza capacitações de forma complementar, além das capacitações admissional e periódica.',
      'Disponibiliza incentivos para a participação da equipe em eventos e capacitações externas.',
    ],
  },
  {
    numero: 6,
    indicador: 'Equipamento de Proteção Individual - EPI',
    criticidade: 'C',
    baseLegal: 'Arts. 108, 142 (§ 2º) e 178 da RDC 1002/2025; item 6.4.1 da Portaria MTP 2.175/2021 e Portaria MTP nº 4.219, de 20/12/2022; Art. 50 (II) da RDC Anvisa 63/2011',
    alternativas: [
      'O serviço não dispõe de nenhum EPI´s para os profissionais ou para os pacientes.',
      'Não existe EPI´s em quantidade ou em condições adequadas de uso para toda a equipe ou todos os pacientes que necessitam o uso ou não disponibiliza as instruções para uso dos EPIs.',
      'Foi identificado profissional ou paciente sem uso de EPI ou não realiza registro da entrega dos EPI´s à equipe.',
      'O serviço possui equipamentos de proteção individual, disponibilizados a toda equipe e compatíveis com os processos de trabalho e de acordo com a NR 32/2022. Os EPI´s possuem Certificados de Aprovação (CA) junto ao Ministério do Trabalho e as entregas à equipe são registradas. No caso de EPI´s para uso de pacientes, esses são regularizados junto a ANVISA. Caso o serviço realize radiografia intraoral, para cada equipamento, existe uma vestimenta plumbífera que garante a proteção do tronco do paciente, incluindo tireoide e gônadas.',
      'Possui sistema informatizado de estoque, indicando as condições de armazenamento e alertas das possíveis data de vencimento dos materiais.',
      'Realiza verificação periódica do uso de EPI´s, pela equipe e pelos pacientes, com os respectivos registros.',
    ],
  },
  {
    numero: 7,
    indicador: 'Segurança do Paciente - NSP e PSP (*Exceto serviço com apenas um consultório individual)',
    criticidade: 'NC',
    baseLegal: 'Arts. 117 e 118 da RDC 1002/2025; Arts. 4º e 7º inciso XI da RDC 36/2013',
    alternativas: [
      'Não possui NSP.',
      'Possui NSP, mas não está formalizado ou não possui Plano de Segurança do Paciente.',
      'O NSP ou o PSP está desatualizado.',
      'O serviço possui Núcleo de Segurança do Paciente (NSP) formalmente constituído pela Direção. Possui Plano de Segurança do Paciente (PSP), sendo contemplados todos os componentes descritos na RDC 1002/2025. Possui protocolos de segurança do paciente implantados e realiza a capacitação dos profissionais do serviço para a execução das atividades previstas nesses protocolos.',
      'Possui estratégias implementadas de avaliação ou monitoramento das ações do NSP, da execução do PSP e do engajamento dos colaboradores/equipe.',
      'O serviço monitora os indicadores previstos nos protocolos de segurança do paciente e a adesão dos profissionais do serviço a esses protocolos.',
    ],
  },
  {
    numero: 8,
    indicador: 'Segurança do Paciente - PP-IRAS',
    criticidade: 'NC',
    baseLegal: 'Arts. 111, 113 e 114 e 119 da RDC 1002/2025',
    alternativas: [
      'Não possui PP-IRAS.',
      'Possui PP-IRAS, mas o plano não está ajustado à realidade local.',
      'Possui PP-IRAS mas não está acessível para consulta por todos os profissionais do serviço de saúde ou não há comprovação de capacitação da equipe assistencial.',
      'O PP-IRAS faz parte da SDBPF e tem ação(ões) implementada(s) no serviço.',
      'O serviço realiza monitoramento de indicadores de implementação e de adesão ao PP-IRAS.',
      'Os resultados do monitoramento dos indicadores são utilizados para promover melhorias na implementação das ações de prevenção e controle de IRAS, RAM e surtos infecciosos.',
    ],
  },
  {
    numero: 9,
    indicador: 'Vigilância e Notificação de Eventos Adversos',
    criticidade: 'NC',
    baseLegal: 'Arts. 119 e 120 da RDC 1002/2025; Arts. 5º (II), 9º e 10 da RDC 36/2013; Art. 8º (III), 23 (XIV) e 62 da RDC 63/2011',
    alternativas: [
      'Não realiza a vigilância e notificação dos eventos adversos ocorridos na instituição ou não realizou notificações de óbito ou os casos de surtos infecciosos.',
      'Realiza a vigilância dos eventos adversos, mas não notifica ao SNVS.',
      'O serviço realiza a vigilância dos eventos adversos, mas não notifica mensalmente ao SNVS ou não notifica em 24h os casos de óbito ou os casos de surtos infecciosos.',
      'O serviço realiza a vigilância dos eventos adversos e notifica regularmente os dados ao SNVS até o 15º dia útil do mês subsequente ao mês de vigilância. Os eventos adversos que evoluírem para óbito ou os casos de surtos infecciosos devem ser notificados em até 24 (vinte e quatro) horas a partir do ocorrido.',
      'Realiza treinamentos frequentes para estimular a notificação de eventos adversos e a cultura de segurança.',
      'Utiliza os resultados obtidos com análise dos indicadores de eventos adversos e investigações para implementação de ações de melhoria e prevenção da recorrência.',
    ],
  },
  {
    numero: 10,
    indicador: 'Gerenciamento de Tecnologias',
    criticidade: 'NC',
    baseLegal: 'Art. 134 a 137 da RDC 1002/2025',
    alternativas: [
      'Não registra as atividades de prestação de assistência técnica, manutenção, calibração e ajuste dos equipamentos ou não realiza manutenção preventiva das incubadoras de indicadores biológicos, anualmente.',
      'Não registra as atividades de prestação de assistência técnica, manutenção, calibração e ajuste de alguns equipamentos.',
      'Não realiza os registros de forma completa ou sistemática ou possuem rasuras ou anotações não legíveis.',
      'Possui registro das atividades de prestação de assistência técnica, manutenção, calibração e ajuste dos equipamentos contendo, no mínimo: a identificação do serviço de assistência odontológica e do equipamento, o detalhamento do serviço e assinatura do responsável pela execução. Realiza as atividades de assistência técnica, manutenção e fabricação conforme orientação do fabricante. Os equipamentos apresentam boas condições de uso, livres de ferrugem e sujidades. As incubadoras de indicadores biológicos passam por manutenção preventiva, no mínimo, anualmente.',
      'Possui sistema informatizado de registro, indicando as condições de uso e periodicidade das manutenções.',
      'Realiza verificação/auditoria periódica nos registros.',
    ],
  },
  {
    numero: 11,
    indicador: 'Testes de Controle de Qualidade, SPR e PPR',
    criticidade: 'NC',
    baseLegal: 'Arts. 141, 146 e 147 da RDC 1002/2025; Anexo I da IN 94/2021 e Anexo I da IN 95/2021; Arts. 28 e 30 da RDC 611/2022',
    alternativas: [
      'Não realiza os testes definidos no Anexo I das IN´s 94 e 95, conforme o tipo de equipamento utilizado ou possui testes em nível de suspensão, mas em funcionamento.',
      'Não possui SPR ou PPR ou possui testes fora da faixa de tolerância, sem nenhuma ação corretiva encaminhada ou não realiza todos os testes e na periodicidade definida nas IN´s ou realizou os testes com instrumentos sem calibração.',
      'O PPR não está atualizado ou os últimos testes ultrapassaram o prazo para realização.',
      'O serviço possui Supervisor de Proteção Radiológica (SPR) formalmente designado e Programa de Proteção Radiológica (PPR) implantado e realiza todos os testes definidos no Anexo I das IN 94 ou IN 95/2021 (conforme o tipo de equipamento) atendendo às respectivas periodicidades, tolerâncias e níveis de restrição. Os testes realizados são comprovados com relatórios, indicando a calibração da instrumentação utilizada.',
      'O PPR é avaliado anualmente, com registro das ações de melhoria.',
      'Possui sistema informatizado indicando as medidas da linha de base dos testes de aceitação e todas as medidas dos testes de constância.',
    ],
  },
  {
    numero: 12,
    indicador: 'Radiologia Odontológica - Equipamentos',
    criticidade: 'NC',
    baseLegal: 'Art. 139, 140, 143 e 145 da RDC 1002/2025; Art 17 (III) da RDC 611/2022',
    alternativas: [
      'Utiliza equipamentos emissores de radiação ionizante nos boxes de Consultórios Coletivos Odontológicos.',
      'Utiliza os equipamentos de forma conflitante com os requisitos do fabricante ou sem cadastro junto a ANVISA.',
      'Utiliza equipamentos sem comunicar a autoridade sanitária local.',
      'O serviço possui inventário dos produtos (incluindo os equipamentos de raios X) sujeitos a regime de vigilância sanitária e de proteção radiológica, com comprovação de cadastro junto à Anvisa, com as informações atualizadas junto a autoridade sanitária local. A utilização de equipamento portátil de radiografia intraoral fica condicionada ao cumprimento dos requisitos informados pelo fabricante.',
      'Utiliza sistema informatizado com possibilidade de acesso à todas as informações e manuais dos equipamentos.',
      'Utiliza cabo disparador com 2 m e suporte para o posicionamento do equipamento.',
    ],
  },
  {
    numero: 13,
    indicador: 'Controle de Pragas',
    criticidade: 'NC',
    baseLegal: 'Inciso VIII do Art. 23 e Art. 63 da RDC 63/2011',
    alternativas: [
      'Não há registro do controle sendo verificada a presença significativa de pragas/vetores na unidade.',
      'Realiza terceirização do serviço, com empresa sem licença sanitária ou não realiza registro do controle, mas não foi identificada a presença de pragas/vetores.',
      'Realiza ações de controle, mas foi verificada a presença eventual de pragas/vetores ou o prazo de validade do controle de pragas/vetores está vencido.',
      'Garante ações eficazes e contínuas de controle de vetores e pragas. Quando necessário, o controle químico é realizado por empresa habilitada, possuidora de licença sanitária e ambiental, com produtos desinfestantes regularizados pela Anvisa. Mantém disponível documentação e registro referente ao controle de vetores e pragas urbanas.',
      'Realiza em periodicidade definida as ações de controle.',
      'Possui rotina de verificação da efetividade do controle, implementando possíveis ações corretivas.',
    ],
  },
  {
    numero: 14,
    indicador: 'Estrutura Física - Ambiente de prestação de assistência odontológica (*Complexidade A sem anestesia)',
    criticidade: 'C',
    baseLegal: 'Art. 14 (inciso I) da RDC 1002/2025',
    alternativas: [
      'Não possui um desses itens: sala com área mín. de 7,5m²; lavatório com água corrente de uso exclusivo para higienização das mãos; bancada de apoio; foco de luz para procedimentos intraorais; ventilação natural que possibilite circulação e renovação de ar; instalação elétrica planejada e dimensionada para os equipamentos, de forma a cumprir com as instruções dos fabricantes.',
      'Dispõe de lavatório com água corrente de uso exclusivo para higienização das mãos, porém sem dispositivo que dispense o contato das mãos com a torneira ou não dispõe de toalhas de papel descartáveis em suporte fechado, sabão líquido com dispensador e lixeira com pedal e tampa ou não dispõe de outros requisitos.',
      'Não dispõe de pelo menos um dos itens obrigatórios para a higienização das mãos ou não possui sistema de climatização que atenda a requisitos específicos dispostos na ABNT NBR 7256.',
      'Dispõe de: a) sala com área mín. de 7,5m²; b) lavatório com água corrente de uso exclusivo para higienização das mãos com dispositivo que dispense o contato das mãos com a torneira; toalhas de papel descartáveis em suporte fechado; sabão líquido com dispensador; e lixeira com pedal e tampa; c) Dispensador de preparação alcoólica para higiene de mãos, devidamente identificado; d) Bancada de apoio; e) Foco de luz para procedimentos intraorais; f) Ventilação natural que possibilite circulação e renovação de ar ou sistema de climatização que atenda a requisitos específicos dispostos na ABNT NBR 7256; e g) Instalação elétrica planejada e dimensionada para os equipamentos, de forma a cumprir com as instruções dos fabricantes.',
      'Apresenta sala com área superior a 7,5m².',
      'Dispõe de dispensadores automáticos para sabão e álcool, sem a necessidade de toque.',
    ],
  },
  {
    numero: 15,
    indicador: 'Estrutura Física - Cons. Individual (*Complexidade A classe I sem sedação inalatória)',
    criticidade: 'C',
    baseLegal: 'Art. 14 (inciso II) da RDC 1002/2025',
    alternativas: [
      'Não possui um desses itens: Sala com área mín. de 9m² e dimensão mín. de 2,20 m; Lavatório com água corrente, exclusivo para higienização das mãos; Bancada de apoio; Instalação de ar comprimido; Instalação de água fria; Instalação elétrica planejada e dimensionada para os equipamentos de forma a cumprir com as instruções dos fabricantes; Compressor de ar adequado para uso em serviços de saúde; Ventilação natural que possibilite circulação e renovação de ar.',
      'Dispõe de lavatório com água corrente de uso exclusivo para higienização das mãos, porém sem dispositivo que dispense o contato das mãos com a torneira ou não dispõe de toalhas de papel descartáveis em suporte fechado, sabão líquido com dispensador e lixeira com pedal e tampa. Ou o compressor de ar está instalado sem proteção acústica (quando dentro do consultório) ou não dispõe de outros requisitos.',
      'Não dispõe de pelo menos um dos itens obrigatórios para a higienização das mãos ou não possui sistema de climatização que atenda a requisitos específicos dispostos na ABNT NBR 7256.',
      'Dispõe de: a) Sala com área mín. de 9m² e dimensão mín. de 2,20 m; b) Lavatório com água corrente, exclusivo para higienização das mãos, com dispositivo que dispense o contato das mãos com a torneira; toalhas de papel descartáveis em suporte fechado; sabão líquido com dispensador; e lixeira com pedal e tampa; c) Dispensador de preparação alcoólica para higiene de mãos, devidamente identificado; d) Bancada de apoio; e) Instalação de ar comprimido; f) Instalação de água fria; g) Instalação elétrica planejada e dimensionada para os equipamentos de forma a cumprir com as instruções dos fabricantes; h) Compressor de ar adequado para uso em serviços de saúde, com proteção acústica quando instalado no interior do consultório e filtro regulador de ar; instalado em local arejado ou com possibilidade de captação do ar externo à edificação, em condições de salubridade e conforme recomendação do fabricante; e i) Ventilação natural que possibilite circulação e renovação de ar ou sistema de climatização que atenda a requisitos específicos dispostos na ABNT NBR 7256.',
      'Apresenta sala com área superior a 9m².',
      'Dispõe de dispensadores automáticos para sabão e álcool, sem a necessidade de toque. Ou compressor de ar instalado em ambiente separado do consultório (sala própria ou área externa coberta).',
    ],
  },
  {
    numero: 16,
    indicador: 'Estrutura Física - Cons. Individual (*Complexidade A classe I com sedação inalatória)',
    criticidade: 'C',
    baseLegal: 'Inciso III e Parágrafos 1º, 2º e 3º do art. 14 da RDC 1002/2025',
    alternativas: [
      'Não possui um dos itens: Sala com área mín. de 9m² e dimensão mín. de 2,20 m; Lavatório com água corrente, exclusivo para higiene das mãos; Bancada de apoio; Instalação de ar comprimido e de água fria; Instalação elétrica planejada e dimensionada para os equipamentos de forma a cumprir com as instruções dos fabricantes; Compressor de ar adequado para uso em serviços de saúde; Ventilação natural; O ambiente segue as orientações do fabricante do equipamento quanto à estrutura física, de modo a garantir segurança eletrostática durante o uso dos gases; Sistema de fornecimento de gases medicinais (oxigênio e óxido nitroso); Sistema de exaustão para diluição de resíduos de gás anestésico.',
      'Dispõe de lavatório com água corrente de uso exclusivo para higienização das mãos, porém sem dispositivo que dispense o contato das mãos com a torneira ou não dispõe de toalhas de papel descartáveis em suporte fechado, sabão líquido com dispensador e lixeira com pedal e tampa. Ou o compressor de ar está instalado sem proteção acústica (quando dentro do consultório) ou não dispõe de outros requisitos.',
      'Os cilindros portáteis de gases não são fixados em carrinhos de transporte ou dispõe de cilindro com volume superior a 10l ou não possui sistema de climatização que atenda a requisitos específicos dispostos na ABNT NBR 7256.',
      'Dispõe de: a) Sala com área mín. de 9m² e dimensão mín. de 2,20 m; b) Lavatório com água corrente, exclusivo para higiene das mãos, que dispensa o contato das mãos com a torneira; toalhas de papel em suporte fechado; sabão líquido com dispensador; e lixeira com pedal e tampa; c) Dispensador de preparação alcoólica para higiene de mãos, identificado; d) Bancada de apoio; e) Instalação de ar comprimido; f) Instalação de água fria; g) Instalação elétrica dimensionada para os equipamentos cumprindo as instruções dos fabricantes; h) Compressor de ar adequado para uso em serviços de saúde, com proteção acústica quando instalado no interior do consultório e filtro regulador de ar; instalado em local arejado ou com possibilidade de captação do ar externo à edificação, em condições de salubridade e conforme recomendação do fabricante; e i) Ventilação natural que possibilite circulação e renovação de ar ou climatização atendendo aos requisitos da ABNT NBR 7256; j) O ambiente segue as orientações do fabricante do equipamento quanto à estrutura física, garantindo a segurança eletrostática durante o uso dos gases; k) Sistema de fornecimento de gases medicinais (oxigênio e óxido nitroso); l) Sistema de exaustão para diluição de resíduos de gás anestésico. Os cilindros portáteis de gases são fixados em carrinhos de transporte. Não dispõe de cilindros portáteis com volume superior a 10 litros e os cilindros quando não estão em uso, são armazenados em ambiente que atende a RDC Anvisa Nº 50/2002.',
      'Ponto de energia elétrica com sistema de emergência (EE) e nobreak.',
      'Dispõe de central de gases medicinais externa, com tubulação dedicada.',
    ],
  },
  {
    numero: 17,
    indicador: 'Estrutura Física - Cons. Individual (*Complexidade A classe II com sedação endovenosa)',
    criticidade: 'C',
    baseLegal: 'Art. 14 (inciso IV) da RDC 1002/2025',
    alternativas: [
      'Não possui um dos itens: Sala com área mín. de 12m² e dimensão mín. de 3,00 m; Lavatório com água corrente, exclusivo para higienização das mãos; Bancada de apoio; Instalação de ar comprimido; Instalação de água fria; Instalação elétrica dimensionada para os equipamentos conforme as instruções dos fabricantes; Compressor de ar adequado para uso em serviços de saúde; Sistema de fornecimento de gases contendo: i. Fonte de Oxigênio (FO); ii. Fonte de Vácuo Clínico (FVC); iii. Fonte de Ar Comprimido Medicinal (FAM), se necessário; iv. Ponto de energia elétrica com sistema de emergência (EE) ou nobreak; Área/sala de recuperação pós-anestésica; Previsão de rota acessível para maca de emergência.',
      'Dispõe de lavatório com água corrente de uso exclusivo para higienização das mãos, porém sem dispositivo que dispense o contato das mãos com a torneira ou não dispõe de toalhas de papel descartáveis em suporte fechado, sabão líquido com dispensador e lixeira com pedal e tampa. Ou o compressor de ar está instalado sem proteção acústica (quando dentro do consultório) ou a área/sala de recuperação pós-anestésica não possui, no mínimo, 10,0 m² por leito de recuperação pós-anestésica ou não dispõe de outros requisitos.',
      'Não dispõe de dispensador de preparação alcoólica para higienização das mãos identificado ou o dispensador encontra-se desabastecido ou não possui porta para passagem de maca de emergência com, no mínimo, 1,10m (vão livre) x 2,10m ou não possui Sistema de ventilação e climatização conforme ABNT NBR 7256.',
      'Dispõe de: a) Sala com área mín. de 12m² e dimensão mín. de 3,00 m; b) Lavatório com água corrente, exclusivo para higienização das mãos, que dispensa o contato das mãos com a torneira; toalhas de papel em suporte fechado; sabão líquido com dispensador; e lixeira com pedal e tampa; c) Dispensador de preparação alcoólica para higiene de mãos, identificado; d) Bancada de apoio; e) Instalação de ar comprimido; f) Instalação de água fria; g) Instalação elétrica dimensionada para os equipamentos cumprindo as instruções dos fabricantes; h) Compressor de ar adequado para uso em serviços de saúde, com proteção acústica quando instalado no interior do consultório e filtro regulador de ar, instalado em local arejado ou com possibilidade de captação do ar externo à edificação, conforme recomendação do fabricante; e i) Sistema de fornecimento de gases contendo: i. Fonte de Oxigênio (FO) - por cilindro ou rede canalizada, com pontos de acesso; ii. Fonte de Vácuo Clínico (FVC) - para aspiração de vias aéreas; iii. Fonte de Ar Comprimido Medicinal (FAM) - se necessário, conforme a indicação dos equipamentos utilizados; iv. Ponto de energia elétrica com sistema de emergência (EE) ou nobreak, para garantir o funcionamento contínuo de monitores, aspiradores, bombas de infusão e outros dispositivos críticos; j) Área/sala de recuperação pós-anestésica, de área mínima de 10,0 m² por leito de recuperação pós-anestésica; k) Porta para passagem de maca de emergência com, no mínimo, 1,10m (vão livre) x 2,10m; l) Previsão de rota acessível para maca de emergência; e m) Sistema de ventilação e climatização que atenda a requisitos específicos dispostos na ABNT NBR 7256.',
      'Sala com dimensão superior a 12m² ou ponto de energia elétrica com sistema de emergência (EE) e nobreak.',
      'Dispõe de central de gases medicinais externa, com tubulação dedicada.',
    ],
  },
  {
    numero: 18,
    indicador: 'Estrutura Física - Cons. Coletivo (*Complexidade A)',
    criticidade: 'C',
    baseLegal: 'Art. 14 (inciso V) da RDC 1002/2025',
    alternativas: [
      'Não possui um dos itens: Boxes com área de 9,0 m² e dimensão mín. de 2,50 m por equipo; Dispositivos de separação entre cadeiras odontológicas; Lavatório com água corrente, exclusivo para higienização das mãos; Bancada de apoio; Instalação de ar comprimido; Instalação de água fria; Instalação elétrica planejada e dimensionada para os equipamentos de forma a cumprir com as instruções dos fabricantes; Compressor de ar adequado para uso em serviços de saúde, instalado em local exclusivo para abrigo do compressor.',
      'Dispositivos de separação das cadeiras odontológicas apresentam altura inferior a 2,0m. Ou lavatório de uso exclusivo para higienização das mãos, sem dispositivo que dispense o contato das mãos com a torneira ou não dispõe de toalhas de papel descartáveis em suporte fechado, sabão líquido com dispensador e lixeira com pedal e tampa ou não dispõe de outros requisitos.',
      'Não dispõe de dispensador de preparação alcoólica para higienização das mãos identificado ou o dispensador encontra-se desabastecido ou não possui Sistema de ventilação e climatização que atenda a requisitos específicos dispostos na ABNT NBR 7256.',
      'Dispõe de: a) Boxes com área de 9,0 m² e dimensão mín. de 2,50 m por equipo de forma a garantir a circulação de pessoas ao redor do equipo; b) A sala possui dispositivos de separação entre cadeiras odontológicas, com altura mín. de 2,0 m; c) Lavatório com água corrente, exclusivo para higienização das mãos, com dispositivo que dispense o contato das mãos com o registro da torneira; toalhas de papel descartáveis em suporte fechado; sabão líquido com dispensador; e lixeira com pedal e tampa; d) Dispensador de preparação alcoólica para higiene de mãos, devidamente identificado; e) Bancada de apoio; f) Instalação de ar comprimido; g) Instalação de água fria; h) Instalação elétrica planejada e dimensionada para os equipamentos de forma a cumprir com as instruções dos fabricantes; i) Sistema de ventilação e climatização que atenda a requisitos específicos dispostos na ABNT NBR 7256; e j) Compressor de ar adequado para uso em serviços de saúde, com proteção acústica e filtro regulador de ar, instalado em local exclusivo para abrigo do compressor com possibilidade de captação do ar externo à edificação e em condições de salubridade, instalado conforme recomendação do fabricante.',
      'Dispõe de dispensadores automáticos para sabão e álcool, sem a necessidade de toque. Ou boxes possuem área superior a 9m².',
      'Ponto de energia elétrica com sistema de emergência (EE) e nobreak.',
    ],
  },
  {
    numero: 19,
    indicador: 'Estrutura Física - Sala de imagem odontológica (*Complexidade A)',
    criticidade: 'NC',
    baseLegal: 'Art. 14 (inciso VI) da RDC 1002/2025',
    alternativas: [
      'Possui instalação de mais de um equipamento emissor de radiação ionizante por sala ou não dispõe de lavatório com água corrente, exclusivo para higienização das mãos.',
      'Não possui instalação elétrica planejada e dimensionada para os equipamentos, de forma a cumprir com as instruções dos fabricantes ou não dispõe de outros requisitos.',
      'Não possui um desses itens: a) Área dimensionada a depender do equipamento de imagem utilizado; d) Projeto de blindagem, conforme preconizado na RDC Anvisa nº 611/2022, para as salas que possuírem equipamento emissor de radiação ionizante.',
      'Dispõe de: a) Área dimensionada a depender do equipamento de imagem utilizado; b) Instalação de apenas um equipamento emissor de radiação ionizante por sala; c) Lavatório com água corrente, exclusivo para higienização das mãos, com dispositivo que dispense o contato das mãos com a torneira; toalhas de papel descartáveis em suporte fechado; sabão líquido com dispensador; e lixeira com pedal e tampa; d) Projeto de blindagem, conforme preconizado na RDC Anvisa nº 611 de 09 de março de 2022 ou a que vier substituí-la, para as salas que possuírem equipamento emissor de radiação ionizante e e) Instalação elétrica planejada e dimensionada para os equipamentos, de forma a cumprir com as instruções dos fabricantes.',
      'Sala de imagem odontológica dispõe de porta automática com intertravamento (o equipamento só dispara se a porta estiver fechada e travada).',
      'Ponto de energia elétrica com sistema de emergência (EE) e nobreak.',
    ],
  },
  {
    numero: 20,
    indicador: 'Estrutura Física - Centro cirúrgico odontológico (CCO) (*Complexidade B)',
    criticidade: 'C',
    baseLegal: 'Art. 24 da RDC 1002/2025',
    alternativas: [
      'Não possui um desses itens: I - Área de recepção/preparo de paciente; II - Lavabo cirúrgico; III - Sala de Cirurgia Odont. com 1 equipo por sala; IV - Área de recuperação pós-anestésica com posto de enfermagem, com nº de macas igual ao nº de salas cirúrgicas; V - Sistema de gases com fontes de oxigênio, vácuo clínico, ar comprimido medicinal e ponto de energia com sistema de emergência; VI - Ventilação e climatização que atenda a ABNT NBR 7256; VII - Expurgo; VIII - Vestiários/sanitários de barreira, masc. e fem.; IX - Área/sala exclusiva para DML com tanque; X - Área adm/área de registro; XI - Área/sala exclusiva para depósito de equip. e materiais; XII - Outros ambientes de apoio.',
      'Área de recuperação pós-anestésica com posto de enfermagem, não possui nº de macas igual ao nº de salas cirúrgicas mais um ou não dispõe de outros requisitos.',
      'Sala de cirurgia com dimensões inferiores às dimensões mínimas.',
      'O CCO dispõe de: I - Área de recepção e preparo de paciente; II - Lavabo cirúrgico; III - Sala de Cirurgia Odontológica com área mín. de 20,0 m², dimensão mín. de 3,45 m e pé-direito útil de 2,7 m. Cada sala contém um único equipo odont.; IV - Área de recuperação pós-anestésica com posto de enfermagem, com nº de macas igual ao nº de salas cirúrgicas mais um; V - Sistema de fornecimento de gases contendo: a) Fonte de Oxigênio (FO); b) Fonte de Vácuo Clínico (FVC); c) Fonte de Ar Comprimido Medicinal (FAM), se necessário; d) Ponto de energia elétrica com sistema de emergência (EE) ou nobreak; VI - Sistema de ventilação e climatização que atenda a requisitos específicos dispostos na ABNT NBR 7256; VII - Expurgo; VIII - Vestiários/sanitários de barreira, masculino e feminino, para funcionários/pacientes; IX - Área/sala exclusiva para DML com tanque; X - Área administrativa/área de registro; XI - Área/sala exclusiva para depósito de equipamentos e materiais; XII - Outros ambientes de apoio considerando a proposta assistencial. Quando o CCO for composto de uma única sala de cirurgia, o vestiário/sanitário pode ser único.',
      'Sala de cirurgia com dimensões superiores ao mínimo e área de recuperação pós-anestésica com nº de macas superior ao nº de salas cirúrgicas mais um.',
      'Ponto de energia elétrica com sistema de emergência (EE) e nobreak.',
    ],
  },
  {
    numero: 21,
    indicador: 'Estrutura Física - Processamento de Dispositivos Médicos',
    criticidade: 'C',
    baseLegal: 'Arts. 25, 26 e Parágrafo único do Art. 29 da RDC 1002/2025',
    alternativas: [
      'Verificado Centro cirúrgico odontológico ou consultório coletivo odontológico utilizando estrutura de bancada ou consultório individualizado utilizando bancada setorizada sem separação por barreira física com altura mín. de 50 cm.',
      'Fluxo não é unidirecional ou sala de processamento não possui sistema de climatização ou as bancadas e cubas não possuem comprimento e profundidade adequados para a atividade e compatíveis com tamanho e volume dos instrumentais ou não dispõe de outros requisitos.',
      'Não dispõe de dispensador de preparação alcoólica para higienização das mãos identificado ou o dispensador encontra-se desabastecido.',
      'O processamento de DM é realizado em uma das seguintes estruturas: I - Bancada setorizada exclusiva para o processamento de dispositivos médicos, dividida em área suja (recepção e limpeza de DM contendo cuba com afastamento mínimo de 30cm em pelo menos um dos lados) e área limpa (para preparo e esterilização de DM com bancada de comprimento mín. de 1m e dimensões compatíveis com os equipamentos, dotada de dispensador identificado de preparação alcoólica para higiene das mãos), separada por barreira física na bancada com altura mín. de 50 cm, que poderá ser locada dentro do consultório ou sala, e será de uso exclusivo destes (não pode ser usado para consultórios coletivos e CCO); II - Sala única e exclusiva, com área de 0,5m² por equipamento odontológico, área mínima de 4,8m², dimensão mín. de 1,3m e sistema de climatização de ar; III - Duas salas, sendo: uma sala de recepção e limpeza com área mín. de 4,8m², contendo bancada e cuba com largura, comprimento e profundidade adequados para a atividade e compatíveis com o tamanho e volume do instrumental a ser lavado; e uma sala de preparo e esterilização com área mín. de 4,8m² e bancada dimensionada a depender do equipamento. O processamento segue fluxo unidirecional, sempre da área suja para limpa.',
      'Áreas da estrutura tipo II ou III superiores ao preconizado na RDC 1002/2025.',
      'Estrutura tipo I apresenta bancada com dimensão superior ao exigido na RDC 1002/2025.',
    ],
  },
  {
    numero: 22,
    indicador: 'Estrutura Física - Processamento de Dispositivos Médicos (*Consultório odontológico coletivo em Instituições de ensino)',
    criticidade: 'C',
    baseLegal: 'Art. 27 da RDC 1002/2025',
    alternativas: [
      'Consultório coletivo odontológico em instituição de ensino utilizando bancada setorizada ou sala única.',
      'O processamento de DM é realizado na estrutura de duas salas, no entanto as salas possuem área menor do que o preconizado ou a bancada ou cuba não são compatíveis com a demanda ou não dispõe de sistema de climatização ou não dispõe de outros requisitos.',
      'Não dispõe de dispensador de preparação alcoólica para higienização das mãos identificado ou o dispensador encontra-se desabastecido.',
      'O processamento de DM é realizado em uma das seguintes estruturas: I - Bancada setorizada exclusiva para o processamento de dispositivos médicos, dividida em área suja (recepção e limpeza de DM contendo cuba com afastamento mínimo de 30cm em pelo menos um dos lados) e área limpa (para preparo e esterilização de DM com bancada de comprimento mín. de 1m e dimensões compatíveis com os equipamentos, dotada de dispensador identificado de preparação alcoólica para higiene das mãos), separada por barreira física na bancada com altura mín. de 50 cm, que poderá ser locada dentro do consultório ou sala, e será de uso exclusivo destes (não pode ser usado para consultórios coletivos e CCO); II - Sala única e exclusiva, com área de 0,5m² por equipamento odontológico, área mínima de 4,8m², dimensão mín. de 1,3m e sistema de climatização de ar; III - Duas salas, sendo: uma sala de recepção e limpeza com área mín. de 4,8m², contendo bancada e cuba com largura, comprimento e profundidade adequados para a atividade e compatíveis com o tamanho e volume do instrumental a ser lavado; e uma sala de preparo e esterilização com área mín. de 4,8m² e bancada dimensionada a depender do equipamento. O processamento segue fluxo unidirecional, sempre da área suja para limpa.',
      'Salas destinadas ao processamento de DM possuem áreas superiores ao mínimo exigido na RDC 1002/2025.',
      'Possui cubas na área de limpeza em quantitativo superior ao exigido.',
    ],
  },
  {
    numero: 23,
    indicador: 'Sala para desinfecção química por imersão (*para serviços que utilizam)',
    criticidade: 'NC',
    baseLegal: 'Art. 33 da RDC 1002/2025',
    alternativas: [
      'Realiza desinfecção química por imersão para os dispositivos médicos de assistência respiratória e não dispõe de sala exclusiva.',
      'Possui sala exclusiva para desinfecção química por imersão, porém não possui sistema de ventilação, climatização e exaustão que atenda aos requisitos da ABNT.',
      'Dispõe de sistema de ventilação, climatização e exaustão conforme a ABNT, porém a sala não está dimensionada de acordo com a demanda ou a cuba para lavagem não possui profundidade suficiente para evitar respingos.',
      'Dispõe de sala exclusiva para desinfecção química por imersão, dimensionada em função da demanda e possui: I - cuba para lavagem com profundidade suficiente para evitar respingos em suas laterais, no piso e no profissional; II - bancada dotada de dispensador de preparação alcoólica para higiene das mãos, devidamente identificado, e com dimensões compatíveis para a acomodação dos DM a serem desinfetados; III - sistema de ventilação, climatização e exaustão que atenda a requisitos específicos dispostos na ABNT — Tratamento de ar em estabelecimentos assistenciais de saúde (EAS) — Requisitos para projeto e execução das instalações.',
      'Dispõe de sensores para monitoramento contínuo de vapores químicos.',
      'Além dos sensores, dispõe de alarmes visuais e sonoros.',
    ],
  },
  {
    numero: 24,
    indicador: 'Monitor multiparâmetros e equipamentos de emergência (*cons. Odont. classe I com sedação inalatória, classe II com sedação endovenosa e o CCO)',
    criticidade: 'C',
    baseLegal: 'Art. 36 da RDC 1002/2025',
    alternativas: [
      'Não dispõe de monitor multiparâmetros e equipamentos de emergência.',
      'Não possui um dos equipamentos de emergência ou os equipamentos não estão em boas condições de uso.',
      'Algum dos equipamentos não está em boa condição de uso.',
      'Dispõe de monitor multiparâmetros e equipamentos de emergência, contemplando no mínimo os seguintes Dispositivos Médicos (DM) e equipamentos: I - termômetro; II - esfigmomanômetro; III - estetoscópio; IV - oxímetro de pulso; V - aspirador de vias aéreas; VI - suporte para fluido endovenoso; VII - carro ou maleta para atendimento de emergência cardiorrespiratória, contendo: a) ressuscitador manual do tipo balão auto-inflável com reservatório e máscara; b) sondas para aspiração; c) materiais e medicamentos emergenciais; e d) desfibrilador externo automático (DEA).',
      'Possui sistema informatizado de registro e controle das calibrações, indicando as respectivas validades.',
      'Possui equipamentos de reserva, calibrados e em condições de uso.',
    ],
  },
  {
    numero: 25,
    indicador: 'DM, equipamentos, aparelhos e mobiliários',
    criticidade: 'NC',
    baseLegal: 'Arts. 37, 38 e 39 da RDC 1002/2025',
    alternativas: [
      'Dispõe de DM e ou equipamentos complementares que não são regularizados na Anvisa (quando aplicável) ou utiliza DM avariados, deteriorados, oxidados ou fora das especificações do fabricante.',
      'Possui equipamentos, utensílios ou móveis, sem condições de uso na(s) área(s) de trabalho.',
      'Possui equipamentos, utensílios e móveis aglomerados ou impedindo, de alguma forma, o desenvolvimento do trabalho ou com pequenas avarias que não impedem o funcionamento ou limpeza.',
      'O serviço é provido de DM e equipamentos complementares regularizados na Anvisa, se aplicável, e que respeitam a legislação vigente. Os DM, equipamentos, aparelhos e mobiliários estão em bom estado de conservação e funcionamento e dentro das especificações ergonômicas, de acordo com as características dos procedimentos executados.',
      'Possui DM, equipamentos, aparelhos e mobiliários de reserva, para possíveis necessidades.',
      'Realiza supervisão periódica para verificar condições de uso e adequação à demanda do serviço.',
    ],
  },
  {
    numero: 26,
    indicador: 'Água para uso no equipo odontológico',
    criticidade: 'NC',
    baseLegal: 'Arts. 40 da RDC 1002/2025',
    alternativas: [
      'A água utilizada para o abastecimento do equipo odontológico não é potável.',
      'Utiliza sistema de purificação da água para abastecer o equipo odontológico, porém não realiza as manutenções corretivas e preventivas.',
      'Utiliza sistema de purificação da água para abastecer o equipo odontológico, porém não realiza as manutenções corretivas e preventivas, conforme orientação do fabricante.',
      'A água utilizada para o abastecimento do equipo odontológico é potável. Caso utilize sistema de purificação para a água de abastecimento do equipo odontológico, realiza manutenção preventiva e corretiva conforme orientação do fabricante, mantendo os registros.',
      'Utiliza os registros para análise de tendência, monitoramento da qualidade da água ou ações corretivas decorrentes dos resultados.',
      'Realiza periodicamente teste de análise da qualidade da água.',
    ],
  },
  {
    numero: 27,
    indicador: 'Mangueiras e reservatórios do equipo',
    criticidade: 'NC',
    baseLegal: 'Arts. 41, 42 e 134 da RDC 1002/2025',
    alternativas: [
      'Mangueiras do equipo odontológico não estão íntegras ou apresentam fissuras ou reservatórios de água apresentam fissuras e sujidade interna.',
      'Reservatórios de água ou as mangueiras do equipo não são drenados e mantidos vazios ao final do expediente de trabalho.',
      'Não realiza ou não registra as manutenções corretivas e preventivas nas mangueiras e reservatórios de água do equipo conforme recomendações do fabricante.',
      'As mangueiras do equipo odontológico estão íntegras e sem sujidade. Mangueiras e reservatórios do equipo são substituídos conforme orientação do fabricante ou quando apresentam fissuras ou perda de integridade e são drenados e mantidos vazios ao final do expediente de trabalho.',
      'Utiliza os registros para análise de tendência, monitoramento da qualidade da água ou ações corretivas decorrentes dos resultados.',
      'Possui protocolo e registro da verificação diária da drenagem.',
    ],
  },
  {
    numero: 28,
    indicador: 'Classificação dos DM',
    criticidade: 'NC',
    baseLegal: 'Arts. 43 e 45 da RDC 1002/2025',
    alternativas: [
      'O serviço não realiza a classificação dos DM.',
      'O serviço classifica os DM, mas não considera a instrução de uso do fabricante.',
      'Foi identificado algum DM sem classificação.',
      'O serviço classifica os DM conforme sua criticidade (não críticos, semicríticos e críticos), conformação (complexos e não complexos) e a instrução de uso do fabricante.',
      'A classificação dos DM´s possui dupla checagem.',
      'Realiza supervisão para verificação da classificação dos DM antes do processamento.',
    ],
  },
  {
    numero: 29,
    indicador: 'Processamento dos DM (Serviço individual classe I)',
    criticidade: 'C',
    baseLegal: 'Art. 44 da RDC 1002/2025',
    alternativas: [
      'O serviço realiza o processamento dos DM durante os horários das atividades clínicas e não utiliza bancada setorizada.',
      'O serviço realiza o processamento no horário das atividades clínicas.',
      'O serviço realiza o processamento fora do horário das atividades clínicas, mas sem bancada setorizada.',
      'O serviço individual classe I realiza o processamento dos DM em bancada setorizada dentro do consultório/sala, somente fora do horário das atividades clínicas.',
      'O serviço possui horário definido, para o processamento, fora do horário das atividades clínicas.',
      'O serviço realiza o processamento em local adequado e fora da sala/consultório.',
    ],
  },
  {
    numero: 30,
    indicador: 'Processamento de DM',
    criticidade: 'C',
    baseLegal: 'Arts. 48, 49, 50, 51, 52 e 53 da RDC 1002/2025',
    alternativas: [
      'O serviço: processa DM incompatíveis com sua capacidade técnico operacional ou em desacordo com classificação ou processa DM não regularizados na Anvisa ou oriundos de explantes para fins de reutilização ou oriundos de procedimentos realizados em animais ou incluindo cirurgias experimentais e produtos de assistência veterinária ou de uso único proibido de ser reprocessado.',
      'Não realiza avaliação do risco potencial do DM semicrítico ou não crítico ter sua classificação alterada para DM crítico durante a prestação da assistência, para que seja utilizado o método de esterilização.',
      'Foi identificado algum DM avariado, deteriorado, oxidado ou fora das especificações do fabricante.',
      'Após limpeza e demais etapas necessárias: DM críticos são submetidos ao processo de esterilização; DM semicríticos são submetidos, no mínimo, ao processo de desinfecção de alto nível; DM semicríticos destinados para o uso em diagnóstico, bem como aqueles utilizados em assistência ventilatória, analgesia e inaloterapia são submetidos à limpeza e, no mínimo, à desinfecção de nível intermediário, com produtos saneantes regularizados pela Anvisa; Produtos não críticos são submetidos, no mínimo, ao processo de desinfecção de baixo nível. A escolha do método de processamento dos DM considera, além da criticidade, o uso pretendido do DM no paciente. Quando há risco potencial do DM semicrítico ou não crítico ter sua classificação alterada para DM crítico durante a prestação da assistência, é utilizado o método de esterilização.',
      'Realiza processo de esterilização dos DM semicríticos.',
      'Realiza processo de esterilização para todos os materiais.',
    ],
  },
  {
    numero: 31,
    indicador: 'Processamento de DM - requisitos gerais',
    criticidade: 'C',
    baseLegal: 'Arts. 54, 55, 56, 57 e 58 da RDC 1002/2025',
    alternativas: [
      'Utiliza método manual de imersão em desinfetantes líquidos para fins de esterilização de DM ou realiza desinfecção de DM com saneantes à base de aldeídos ou realiza a desinfecção de tubete de medicamento anestésico por imersão.',
      'Não possui POP para processamento dos DM.',
      'O processamento dos DM ocorre em desacordo com o POP.',
      'O processamento dos DM segue Procedimento Operacional Padrão - POP detalhado para cada etapa, elaborado pelo RT, com base em evidência objetiva, referencial científico atualizado e normatização pertinente. O serviço garante que os dispositivos médicos, equipamentos, saneantes e embalagens de esterilização são utilizados exclusivamente para os fins a que se destinam.',
      'Realiza avaliação periódica, com análise crítica e registro de melhorias no POP.',
      'Realiza supervisão periódica para verificação de cumprimento do POP.',
    ],
  },
  {
    numero: 32,
    indicador: 'Processamento de DM - pré-limpeza',
    criticidade: 'C',
    baseLegal: 'Arts. 59 e 60 da RDC 1002/2025',
    alternativas: [
      'Não realiza a pré-limpeza dos DM ou os DM ficam imersos em solução de detergente durante o processo de pré-limpeza no ponto de assistência.',
      'Não realiza a pré-limpeza imediatamente após o uso.',
      'Foi identificado algum DM sem pré-limpeza imediata após o uso.',
      'Imediatamente após o atendimento de cada paciente, é realizada pré-limpeza nas superfícies internas e externas dos DM, bem como das turbinas de alta rotação.',
      'Realiza verificação periódica do processo de pré-limpeza.',
      'Realiza verificações periódicas durante o dia, para identificar possíveis DM sem pré-limpeza imediata.',
    ],
  },
  {
    numero: 33,
    indicador: 'Processamento de DM - limpeza',
    criticidade: 'C',
    baseLegal: 'Arts. 61, 62 e 65 da RDC 1002/2025',
    alternativas: [
      'DM não são submetidos a limpeza manual antes da desinfecção/esterilização ou limpeza dos DM de conformação complexa não é complementada por limpeza automatizada.',
      'Utilizam acessórios inadequados (abrasivos, que liberam partículas, não são mantidos limpos e secos quando não estão em uso e descartados quando sua função está comprometida).',
      'Não realiza limpeza manual de todos os produtos críticos antes da lavagem automatizada.',
      'Antes de sua desinfecção ou esterilização, o DM passível de processamento é submetido ao processo de limpeza manual, realizada com objetos adequados (não abrasivos, que não liberam partículas, mantidos limpos e secos quando não estão em uso e descartados quando sua função está comprometida). O DM de conformação complexa tem sua limpeza complementada por limpeza automatizada em cuba ultrassônica ou outro equipamento que possua indicação do fabricante.',
      'Complementada com limpeza automatizada, em cuba ultrassônica, todos os DM.',
      'Realiza também registro visual (micro imagem ou filme) do monitoramento da limpeza.',
    ],
  },
  {
    numero: 34,
    indicador: 'Processamento - dispositivos canulados',
    criticidade: 'C',
    baseLegal: 'Arts. 67 e 68 da RDC 1002/2025',
    alternativas: [
      'Objetos utilizados na escovação interna manual dos canulados não possuem dimensões compatíveis e não utiliza a cuba ultrassônica.',
      'Cuba ultrassônica não utiliza fluxo intermitente ou outra tecnologia compatível. Ou não dispõe de pistola de água sob pressão para limpeza e enxague dos canulados.',
      'Dispõe de pistola de água sob pressão para limpeza e enxague de DM canulados, porém não dispõe de adaptadores compatíveis para no mínimo um dos DM canulados.',
      'Para escovação interna manual de produtos canulados, utiliza objetos próprios para esta finalidade e com dimensões compatíveis. Quando da indisponibilidade de objetos compatíveis, realiza a limpeza automatizada em cuba ultrassônica com conector para canulados e que utiliza fluxo intermitente ou outra tecnologia compatível. Utiliza pistola de água sob pressão para limpeza e enxague, com adaptadores compatíveis com os DM canulados.',
      'Possui canulados reserva para possíveis substituições imediatas.',
      'Existe supervisão periódica para verificação do cumprimento das normas e medidas corretivas são adotadas e registradas.',
    ],
  },
  {
    numero: 35,
    indicador: 'Processamento de DM - água para limpeza e enxague',
    criticidade: 'C',
    baseLegal: 'Arts. 63 e 64 da RDC 1002/2025',
    alternativas: [
      'Água para limpeza ou enxague não é, no mínimo, potável.',
      'Água utilizada na limpeza automatizada é potável, mas não atende às especificações do fabricante.',
      'Não verifica se a qualidade da água é a especificada pelos fabricantes dos equipamentos.',
      'Água utilizada para limpeza e enxague de DM é, no mínimo, potável. A água utilizada nos equipamentos de limpeza automatizada atende às especificações dos fabricantes dos equipamentos.',
      'Conta com dois tipos de enxágue: água potável para lavagem de todos os DM e água purificada para enxágue final de todos os DM.',
      'Realiza controle mensal da qualidade da água e registra.',
    ],
  },
  {
    numero: 36,
    indicador: 'Processamento de DM - secagem e avaliação da limpeza e integridade',
    criticidade: 'C',
    baseLegal: 'Arts. 70, 71 e 72 da RDC 1002/2025',
    alternativas: [
      'Utiliza materiais absorventes não descartáveis ou reciclados. Não dispõe ar comprimido medicinal, gás inerte ou ar filtrado, seco e livre de óleo para secagem interna do canulados.',
      'Não dispõe de todos os equipamentos e materiais específicos para realização da secagem e avaliação da limpeza ou utiliza produtos não autorizados para uso hospitalar (ex: secadora doméstica).',
      'Avalia a limpeza e integridade dos DM por amostragem.',
      'A secagem dos DM é realizada com secadoras, ar comprimido medicinal, gás inerte ou ar filtrado, seco e livre de óleo, ou materiais absorventes descartáveis não recicláveis; nos canulados, utiliza adaptadores compatíveis para garantir a secagem interna. Após cada limpeza, avalia a limpeza e a integridade dos DM por inspeção visual com lentes de aumento de pelo menos oito vezes, além de verificar e registrar periodicamente a funcionalidade dos dispositivos.',
      'Possui plano de contingência com reserva operacional para substituição de equipamentos e materiais.',
      'Possui protocolo para verificação dos equipamentos e materiais, avaliando sistematicamente quanto ao funcionamento e integridade.',
    ],
  },
  {
    numero: 37,
    indicador: 'Processamento de DM - produtos saneantes',
    criticidade: 'C',
    baseLegal: 'Art. 66 da RDC 1002/2025',
    alternativas: [
      'Faz uso de saneantes que não são específicos para limpeza e desinfecção de DM ou não são regularizados junto à Anvisa.',
      'Utiliza saneantes regularizados junto à Anvisa, específicos para limpeza e desinfecção de DM, porém em desacordo às instruções do fabricante (ex. diluição e temperatura) ou não troca a cada uso a solução detergente utilizada para imersão de DM.',
      'Realiza a diluição de detergentes sem o uso de recipientes graduados ou dosadores, impedindo a comprovação da exatidão da diluição.',
      'Utiliza produtos saneantes regularizados junto à ANVISA, específicos para a limpeza e desinfecção de DM, em conformidade às instruções de uso dos fabricantes. Faz uso de recipiente graduado para diluição dos detergentes, conforme instruções dos fabricantes e troca a solução detergente utilizada para imersão de DM a cada uso.',
      'Registra o produto utilizado, diluição, tempo de contato e responsável pela execução em planilhas ou sistema, garantindo o histórico.',
      'Realiza e registra a supervisão periódica do processo de diluição.',
    ],
  },
  {
    numero: 38,
    indicador: 'Processamento de DM - preparo e acondicionamento - embalagens',
    criticidade: 'C',
    baseLegal: 'Arts. 73, 74, 75, 76, 77 e 82 (§2) da RDC 1002/2025',
    alternativas: [
      'Utiliza qualquer das embalagens a seguir para esterilização: caixas metálicas sem perfurações, embalagens de papel kraft, papel toalha, papel manilha, papel jornal, lâminas de alumínio, embalagens plásticas em ambos os lados. Reutiliza embalagens descartáveis ou utiliza embalagem de tecido não íntegra.',
      'Realiza o fechamento de embalagens de papel grau cirúrgico com indicador tipo 1 (fita zebrada) ou com equipamentos não específicos para esta finalidade ou não deixa margens de selagem adequadas que permitam a abertura asséptica do pacote.',
      'Utiliza embalagens de grau cirúrgico para esterilização em conformidade com o processamento realizado, porém com prazo de validade vencido ou utiliza embalagens de tecido de algodão, porém não possui plano contendo os critérios de aquisição e substituição do arsenal de embalagens.',
      'Embalagens utilizadas são específicas para esterilização de DM e destinadas a esta finalidade. São dimensionadas para permitir a circulação do vapor entre os DM e a abertura asséptica. A selagem das embalagens é feita conforme orientação do fabricante ou por termoseladora; quando de tecido de algodão, está íntegra, sem remendos, cerzidos, rasgos ou perfurações. O serviço dispõe de plano com critérios de aquisição e substituição do arsenal de embalagem de tecido mantendo os registros.',
      'Possui ações de controle sobre a integridade e condições de barreira antimicrobiana das embalagens com dados registrados no setor.',
      'Realiza supervisão periódica para verificação das ações de controle sobre a integridade e condições de barreira antimicrobiana das embalagens com dados registrados no setor.',
    ],
  },
  {
    numero: 39,
    indicador: 'Processamento de DM - preparo, acondicionamento - identificação',
    criticidade: 'NC',
    baseLegal: 'Arts. 78, 79, 80 e 81 da RDC 1002/2025',
    alternativas: [
      'Pacote a ser submetido a esterilização não está identificado ou não dispõe de indicador tipo 1.',
      'Pacote a ser submetido a esterilização está identificado, porém as informações estão incompletas ou fixa a etiqueta de identificação na embalagem após a esterilização.',
      'Pacote a ser submetido a esterilização está identificado, porém algumas informações estão rasuradas, borradas ou a identificação foi realizada em local errado.',
      'O pacote a ser submetido à esterilização, dispõe de embalagem com indicador tipo 1 e está identificado por meio de etiqueta contendo, no mínimo, data da esterilização, nome do responsável pelo preparo, lote da carga de esterilização e identificação dos DM incluídos no pacote, se a embalagem não for transparente. A etiqueta é aplicada sobre a embalagem antes do processo de esterilização e nos casos de uso do papel grau cirúrgico, está fixada sobre a parte plástica ou a identificação é direta na embalagem com caneta adequada.',
      'Pacotes submetidos à esterilização estão identificados por meio de etiquetas com código de barras.',
      'Realiza supervisão periódica para verificação do acondicionamento e identificação das embalagens.',
    ],
  },
  {
    numero: 40,
    indicador: 'Processamento de DM - prazo de validade da esterilização',
    criticidade: 'NC',
    baseLegal: 'Art. 82 da RDC 1002/2025',
    alternativas: [
      'Serviço estabelece prazos de validade da esterilização superiores a 06 meses, mesmo sem possuir validação científica ou não reprocessa o material antes do uso nos casos que há suspeita ou evidência de violação da embalagem, umidade, sujidade, dano físico ou alteração nas condições de armazenamento.',
      'A data limite de uso dos DM esterilizados excede a data de validade da embalagem.',
      'Foi identificado algum material sem o prazo de validade ou com a validade vencida.',
      'Serviço estabelece o prazo de validade da esterilidade dos pacotes processados em autoclave, considerando validação científica do prazo de guarda por meio de estudos próprios ou consultorias especializadas e assegura que o período de armazenamento é compatível com a manutenção da esterilidade. Caso não exista validação científica do prazo de validade da esterilidade, estabelece o prazo de 6 (seis) meses, contados a partir da data do processamento, desde que a embalagem permaneça íntegra, seca, armazenada em condições ambientais adequadas, sem sinais de violação, umidade, sujidade ou dano físico. Registra o prazo de validade no POP de processamento do serviço. Quando há suspeita ou evidência de violação da embalagem, umidade, sujidade, dano físico ou alteração nas condições de armazenamento, o material é reprocessado antes do uso, independentemente do prazo estabelecido. A data limite de uso dos DM não excede a data de validade da embalagem.',
      'Possui protocolo de verificação de validade e retirada do produto antes do vencimento.',
      'Possui sistema informatizado de controle do material processado, indicando data do processamento, data do uso e alerta em caso de vencimento da validade.',
    ],
  },
  {
    numero: 41,
    indicador: 'Processamento de DM - esterilização',
    criticidade: 'C',
    baseLegal: 'Arts. 86 e 87 da RDC 1002/2025',
    alternativas: [
      'Faz uso de estufas ou caixas de luz ultravioleta na esterilização de DM utilizados na assistência odontológica.',
      'Dispõe os pacotes de forma empilhada ou em contato com as paredes da câmara do esterilizador ou a quantidade de pacotes de cada carga é superior à capacidade da autoclave.',
      'Não garante que, no caso de uso de grau cirúrgico, os pacotes quando organizados lado a lado na vertical, são organizados de forma que a face de papel esteja em contato com papel e plástico com plástico.',
      'Utiliza equipamentos com tecnologia de esterilização compatível com os dispositivos médicos a serem esterilizados, conforme instruções do fabricante. Organiza os pacotes dentro da câmara do esterilizador considerando a capacidade, o posicionamento e o espaço entre os pacotes, afastados das paredes internas da câmara. No caso de uso de grau cirúrgico, os pacotes quando organizados lado a lado na vertical, são organizados de forma que a face de papel esteja em contato com papel e plástico com plástico. Água utilizada nos equipamentos de esterilização atende às especificações dos fabricantes dos equipamentos.',
      'Realiza dupla checagem da carga para esterilização.',
      'Realiza supervisão periódica para verificação do processo de esterilização.',
    ],
  },
  {
    numero: 42,
    indicador: 'Processamento de DM - esterilização - indicadores',
    criticidade: 'C',
    baseLegal: 'Arts. 88, 89, 90, 91 e 92 da RDC 1002/2025',
    alternativas: [
      'Não realiza nenhum monitoramento da esterilização ou não realiza teste de Bowie & Dick (autoclave assistida por bomba de vácuo) ou não realiza medidas adequadas diante da reprovação de testes de controle de qualidade.',
      'Não realiza o monitoramento com todos os indicadores ou não registra corretamente (parâmetros físicos, resultado do teste, carga, data e operador) o monitoramento da esterilização ou não realiza o monitoramento semanal biológico.',
      'Realiza o monitoramento com todos os parâmetros, mas os registros estão incompletos ou o pacote teste não é preparado com embalagem dupla de papel grau cirúrgico.',
      'Monitora semanalmente a esterilização com pacote teste contendo um indicador biológico e um integrador químico tipo 5 ou 6, no primeiro ciclo do dia. Esse pacote é preparado com embalagem dupla de papel grau cirúrgico e posicionado no ponto de menor circulação de calor indicado pelo fabricante do equipamento. Nos ciclos subsequentes utiliza-se pacote teste contendo um integrador químico tipo 5 ou 6. O monitoramento da esterilização de cada carga de DM é registrado, contendo, no mínimo: I - data da esterilização; II - número do lote da carga de esterilização; III - identificação do equipamento esterilizador, quando houver mais de um; IV - resultado e interpretação do pacote teste; V - relação de pacotes esterilizados; VI - nome do operador do equipamento; e VII - parâmetros físicos do processo de esterilização (vapor saturado pressão, os parâmetros são tempo, temperatura e pressão). Os registros são arquivados de forma a garantir a sua rastreabilidade, por um prazo mínimo de 5 (cinco) anos. Na autoclave assistida por bomba de vácuo, realiza teste para avaliar o desempenho do sistema de remoção de ar (Bowie & Dick), no primeiro ciclo do dia.',
      'O monitoramento é registrado em sistema informatizado, com indicação de alertas para periodicidade e resultados.',
      'Realiza o monitoramento com indicador biológico mais de uma vez por semana.',
    ],
  },
  {
    numero: 43,
    indicador: 'Processamento de DM - desinfecção química (*aplicável a serviços que processam DM de assistência ventilatória)',
    criticidade: 'NC',
    baseLegal: 'Arts. 94, 95, 96, 97, 98, 99, 100 e 101 da RDC 1002/2025',
    alternativas: [
      'Não possui sala própria para a desinfecção química por imersão de dispositivos médicos de assistência ventilatória.',
      'Não realiza a monitorização dos parâmetros indicadores de efetividade definidos pelo fabricante, antes do início da atividade ou o modo de uso da solução desinfetante não atende a recomendação do fabricante.',
      'Produtos passam por desinfecção, mas o processo difere dos POP´s.',
      'A desinfecção química (DQ) por fricção é realizada na bancada da área limpa em qualquer ambiente de processamento. A desinfecção de dispositivos médicos (DM) de assistência ventilatória ocorre em sala própria para DQ por imersão, após o processo de limpeza. O desinfetante para DM semicríticos são utilizados conforme orientação do fabricante, respeitando os tempos de exposição, e garante-se a completa imersão do DM na solução desinfetante em recipiente exclusivo, rígido, liso, com fechamento estanque, passível de limpeza e desinfecção, devidamente identificado. Realiza a monitorização dos parâmetros indicadores de efetividade definidos pelo fabricante antes do início da atividade, com registro dos resultados mantidos por pelo menos cinco anos e disponíveis à autoridade sanitária. A água utilizada no enxágue atende aos padrões de potabilidade e, quando não houver uso imediato, os DM são embalados em material limpo e seco que assegura barreira física, identificados com data e responsável pela desinfecção, e acondicionados de forma a prevenir recontaminação e manter a integridade e rastreabilidade até o momento do uso.',
      'Realiza monitoração de parâmetros além dos indicados pelos fabricantes.',
      'Existe supervisão periódica para verificação do processamento de DM por desinfecção química.',
    ],
  },
  {
    numero: 44,
    indicador: 'Processamento de DM - armazenamento',
    criticidade: 'NC',
    baseLegal: 'Art. 102 da RDC 1002/2025',
    alternativas: [
      'O armazenamento dos DM é realizado em condições que não favorecem a integridade da embalagem (local úmido, próximo a sifões de pia, sob luz direta) ou foi identificado algum material não estéril no armário de estéril.',
      'Não possui local exclusivo para armazenamento.',
      'Armazena os DM de forma que não permite manipulação mínima.',
      'Os DM esterilizados são armazenados em local seco, protegido da luz solar direta e exclusivo, que favorece a manipulação mínima e garante a integridade da embalagem.',
      'Possui controle de acesso ao local de armazenamento.',
      'Possui controle e registro das condições ambientais ou realizar supervisão periódica das condições de armazenamento.',
    ],
  },
  {
    numero: 45,
    indicador: 'Processamento externo ao serviço',
    criticidade: 'C',
    baseLegal: 'Arts. 105 e 106 da RDC 1002/2025',
    alternativas: [
      'Terceiriza o processamento em empresa que não é empresa processadora ou não está regularizada junto a autoridade sanitária ou envia os DM sem o preparo prévio no serviço que presta assistência odontológica.',
      'Terceiriza o processamento em empresa regularizada junto a autoridade sanitária, mas não possui contrato de terceirização ou não existe POP de preparo prévio definido em conjunto pela empresa contratada e o serviço de saúde contratante.',
      'Existe contrato de terceirização assinado, mas com validade expirada ou o contrato não estabelece as responsabilidades das partes.',
      'O processamento de DM é terceirizado por meio de empresa processadora regularizada junto a autoridade sanitária, formalizada mediante contrato de prestação de serviço. Antes de serem encaminhados para empresa processadora, os DM são submetidos ao preparo prévio no serviço que presta assistência odontológica e existe POP de preparo prévio definido em conjunto pela empresa contratada e o serviço de saúde contratante.',
      'Possui termo de referência para qualificação do fornecedor e contratação da empresa processadora.',
      'O serviço realiza auditoria periódica na empresa processadora.',
    ],
  },
  {
    numero: 46,
    indicador: 'Atendimento de urgência/emergência',
    criticidade: 'C',
    baseLegal: 'Art. 116 da RDC 1002/2025',
    alternativas: [
      'Não possui protocolo.',
      'O protocolo estabelece procedimentos incompatíveis com a realidade do serviço.',
      'O protocolo não é de fácil acesso ou não é de conhecimento de toda a equipe.',
      'O serviço possui protocolo de atendimento e encaminhamento dos pacientes em caso de urgências e emergências, constando as situações em que o paciente pode ser atendido localmente ou que precisa ser estabilizado e encaminhado para atendimento fora do serviço odontológico, incluindo a determinação que o serviço preste assistência a todos os pacientes até a chegada da ambulância ou a transferência segura para atendimento em uma unidade de pronto atendimento de urgências ou um hospital.',
      'O serviço realiza simulações periódicas, com a equipe, para atendimentos de urgência/emergência.',
      'Possui protocolo atualizado e plano de capacitação admissional e periódica para atendimento de urgência/emergência no próprio serviço.',
    ],
  },
  {
    numero: 47,
    indicador: 'Gerenciamento de Resíduos de Serviços de Saúde (GRSS)',
    criticidade: 'NC',
    baseLegal: 'Arts. 122 a 129 e 137 da RDC 1002/2025; Arts. 2º(I) e 5º(I) da RDC 222/2018',
    alternativas: [
      'Não dispõe de coletores/lixeiras em quantidade suficiente ou não realiza limpeza e esterilização do DM, antes de ser encaminhado para disposição final ou possui caixa de perfuro cortantes danificada ou com resíduos ultrapassando o limite de preenchimento.',
      'Dispõe dos coletores em quantidade insuficiente, ou não estão identificados corretamente ou são verificadas falhas na segregação dos resíduos.',
      'Lixeiras ou coletores em quantidade suficiente, identificados, porém alguns estão danificados ou sem tampa de acionamento por pedal.',
      'Dispõe de lixeiras ou coletores compatíveis com o tipo de resíduo gerado/produzido pela unidade, devidamente identificados, em boas condições com tampa e acionamento por pedal. O resíduo oriundo de explante de DM deve ser submetido ao processo de limpeza e esterilização, antes de ser encaminhado para disposição final. Caso sejam constituídos de componentes desmontáveis, após a esterilização devem ser acondicionados de forma a impedir a remontagem.',
      'Lixeiras ou coletores são de acionamento automático.',
      'Coletores possuem tampa hermética.',
    ],
  },
  {
    numero: 48,
    indicador: 'Responsável Técnico (RT) - Laboratório de Prótese',
    criticidade: 'NC',
    baseLegal: 'Art. 158 da RDC 1002/2025',
    alternativas: [
      'O serviço não possui RT do laboratório.',
      'O RT não está presente durante todo o funcionamento do serviço.',
      'O RT não está formalmente designado.',
      'O laboratório funciona com a presença física do responsável técnico (RT).',
      'Além de RT, possui Substituto designado.',
      'O RT possui curso formal de especialização na área de prótese dentária.',
    ],
  },
  {
    numero: 49,
    indicador: 'Laboratório de Prótese - Estrutura Física (*aplicado somente a laboratórios vinculados)',
    criticidade: 'NC',
    baseLegal: 'Arts. 163, 164, 165 e 169 da RDC 1002/2025',
    alternativas: [
      'A área de trabalho é instalada em corredores com acesso a outras dependências ou utiliza os equipamentos destinados aos trabalhos de prótese dentária para o preparo ou aquecimento de alimentos.',
      'A área de trabalho é instalada sem separação do serviço de assistência odontológica ou não possui as áreas mínimas.',
      'A separação de parede ou divisória não é até o teto ou o espaço mínimo entre as bancadas é menor que 1m.',
      'O laboratório vinculado possui área de trabalho com largura mínima de 1,5m, incluindo 0,60m para bancada de trabalho. Quando houver duas bancadas, o espaço mínimo entre elas deve ser de 1,0m. A área de trabalho é separada do serviço de assistência odontológica, por parede ou divisória até o teto, e com porta que impede a comunicação direta entre ambos. Caso o Laboratório utilize exclusivamente o escaneamento digital e computador para produção de imagens dos modelos, a metragem pode ser reduzida. O laboratório possui, no mínimo: I - Bancada de trabalho; II - Pia exclusiva para trabalhos com caixa de decantação para resíduos de gesso; III - Local exclusivo para arquivo de requisições de serviços; IV - Local exclusivo para armazenagem e guarda de instrumental e produtos; V - Local exclusivo para Depósito de Material de Limpeza (DML); VI - Local exclusivo para guarda de Equipamento de Proteção Individual (EPI); e VII - Local exclusivo para copa, quando houver consumo ou preparo de alimentos no LPD.',
      'O laboratório possui áreas dimensionadas em conformidade e com capacidade de ampliar as atividades dos serviços.',
      'O laboratório possui áreas separadas e independentes do serviço.',
    ],
  },
  {
    numero: 50,
    indicador: 'Laboratório de Prótese - equipamentos',
    criticidade: 'NC',
    baseLegal: 'Arts. 171, 172, 173 e 174 da RDC 1002/2025',
    alternativas: [
      'Os equipamentos de gases combustíveis são mantidos próximos de fontes de calor ou possui equipamentos de uso exclusivamente odontológico, tais como, cadeira odontológica, cuspideira e itens que configurem o atendimento de pacientes.',
      'A fundição, caso exista, não possui sistema de exaustão de gases.',
      'O compressor de ar comprimido é colocado na área de trabalho sem proteção acústica.',
      'Os equipamentos de gases combustíveis são mantidos afastados de fontes de calor e as tubulações devem seguir a legislação específica, preconizada pela ABNT. A fundição, caso exista, possui sistema de exaustão de gases. O compressor de ar comprimido é colocado fora da área de trabalho ou, caso instalado em área interna, possui proteção acústica.',
      'Compressor em área externa e adequada.',
      'Não utiliza fundição.',
    ],
  },
  {
    numero: 51,
    indicador: 'Laboratório de Prótese - insumos e armazenamento',
    criticidade: 'NC',
    baseLegal: 'Arts. 180 e 181 da RDC 1002/2025',
    alternativas: [
      'O serviço utiliza materiais sem regularização junto a ANVISA, mesmo quando o material deveria ser regularizado ou não conserva/estoca os materiais no interior do serviço ou realiza fracionamento sem rotulagem.',
      'Realiza armazenamento sem seguir as orientações dos fabricantes dos materiais.',
      'Realiza fracionamento, identificando com rótulos contendo informações incompletas.',
      'O serviço utiliza materiais regularizados junto a Anvisa, se aplicável, estando estocados e conservados no interior do estabelecimento, respeitando as orientações do fabricante. Quando realiza fracionamento dos materiais, estes são rotulados e identificados. O rótulo possui número do lote, data de fabricação, data de validade, nome do fabricante, data do fracionamento e identificação do responsável pelo fracionamento.',
      'Possui sistema informatizado de estoque, indicando as condições de armazenamento e alertas das possíveis data de vencimento dos materiais.',
      'Quando realiza fracionamento, utiliza rotulagem com impressão padronizada, contendo todas as informações necessárias ao rótulo e possibilitando rastreabilidade.',
    ],
  },
];
